elastic/docs-content

.github/CODEOWNERS
.github/ISSUE_TEMPLATE/community-request.yaml
.github/ISSUE_TEMPLATE/internal-request.yaml
README.md

This PR adds a basic readme, codeowners, and issue templates to make the repo more welcoming to external contributors.
- **README**: this is intended to be a lightweight readme, and should be extended with additional contribution guidelines and a public mdx component reference when we have one available.
- **issue templates** are based on the public templates currently in use in the observability and security repos.
- the **codeowners** file will be extended when we add actions that need to be managed by eng.
open question: I have a link to docs.elastic.dev available for internal contributors. I think this is ok because we are labeling it as internal, and it will be hard for contributors to find otherwise. open to other opinions.

Add templates, codeowners, readme

---

serverless/nav/serverless-elasticsearch.docnav.json
serverless/pages/search-playground.mdx

Creates a presence for Playground in serverless docs, and points users to Kibana docs where content currently lives.

Add ES3 Playground stub page

---

serverless/pages/action-connectors.mdx

Adds link to connector docs added in https://github.com/elastic/kibana/pull/183792.

Add Obs AI connector to connectors list in serverless

---

serverless/pages/action-connectors.mdx

This PR updates the list of connectors in https://docs.elastic.co/serverless/action-connectors
It adds a link to the new Cases connector, and updates the versions in some of the existing connector links.
Relates to https://github.com/elastic/docs-content/pull/16
https://docs-elastic-h3895kt64-elastic-dev.vercel.app/serverless/action-connectors

[Serverless] Add link to Cases connector

---

help-center/connector-client.mdx

https://github.com/elastic/platform-docs-team/issues/376
Because the connector setup and self-managed service deployment involves a lot of terminal work, I'm not super sure how **Help**ful this content will be in help center.
I tried to cut the content down as much as possible compared to the equivalent [ES3 docs page](https://docs.elastic.co/serverless/elasticsearch/ingest-data-through-integrations-connector-client), but no worries if it doesn't make sense to add this page. 
Please 🙏 :
- Check for MDX formatting issues 
- Test the steps work

Add connectors help center article

---

serverless/pages/manage-your-project-rest-api.mdx

This will update our documentation to point to the api spec hosted on bump.sh

CP-7016 update serverless api spec links to point to bump.sh

---

serverless/pages/welcome-to-serverless.mdx

This is a non-visible change to indicate that the new build pipeline is successful and live on https://www.elastic.co/docs. Safe to merge this once out of draft

Update welcome-to-serverless.mdx to force a build

---

serverless/pages/data-views.mdx
serverless/pages/index-management.mdx
serverless/pages/ingest-pipelines.mdx
serverless/pages/logstash-pipelines.mdx
serverless/pages/machine-learning.mdx
serverless/pages/maintenance-windows.mdx
serverless/pages/saved-objects.mdx

This PR fixes the capitalization of feature names in https://www.elastic.co/docs/current/serverless/project-settings to align with https://eui.elastic.co/#/guidelines/writing/guidelines#capitalization. The pages in this section previously used the type of capitalization appropriate for apps, but IMO these pages should evolve to be more generic introductions to these features.

Fix capitalization in management page titles

---

serverless/nav/serverless-general.docnav.json
serverless/pages/manage-billing-stop-project.mdx

This adds the following to the Billing section of the serverless docs. The content is based on the example provided in the parent issue (thanks @mrjoechin!) with only very minor changes.
Closes: https://github.com/elastic/docs-content/issues/31
---

Add 'Stop charges for a project' page

---

serverless/pages/manage-billing.mdx

Earlier today I added a new page about stopping charges for a project ([PR](https://github.com/elastic/docs-content/pull/36)) but I clumsily forgot to add a link to that new page from the main [Manage billing](https://www.elastic.co/docs/current/serverless/general/manage-billing) page. So, this adds in that missing link. It's not grouped with the other links because it's not part of the "Billing" flow that the other tasks are part of.
---

Add link to new stop billing page

---

serverless/pages/clients-java-getting-started.mdx

Updating the documentation so that the jackson-databind dependency matches the one used by the java client.

Java client jackson dependency update

---

serverless/pages/action-connectors.mdx

Relates to https://github.com/elastic/kibana/pull/183668
This PR adds the Google Gemini connector to the list of connectors in https://www.elastic.co/docs/current/serverless/action-connectors, since it's now visible in security projects on production.
It also updates the links to use variables.  At this moment, since the Gemini connector doesn't exist in "current" docs, that URL has to be hard-coded.

Add Google Gemini connector

---

serverless/pages/apis-http-apis.mdx

This PR fixes a broken link on https://www.elastic.co/docs/current/serverless/elasticsearch/http-apis

Fix link to APIs

---

serverless/pages/clients-php-getting-started.mdx
serverless/pages/developer-tools-troubleshooting.mdx
serverless/pages/search-your-data-the-search-api.mdx

We have some 404s due to old relative links

Fix 404 links to serverless API ref

---

serverless/pages/get-started.mdx
serverless/pages/manage-billing-monitor-usage.mdx
serverless/pages/manage-billing-pricing-model.mdx
serverless/pages/manage-billing.mdx
serverless/pages/pricing.mdx
serverless/pages/sign-up.mdx
serverless/partials/minimum-vcus-detail.mdx
serverless/partials/minimum-vcus.mdx

To resolve confusion about the ES serverless pricing model, I'm adding more explicit detail about how the minimum # of running VCUs impact billing, and what those minimum VCUs are used for.
The following pages got additional info, largely in the form of caution blocks:
[Elasticsearch billing dimensions](https://elastic-dot-co-docs-production-dng2tyfar-elastic-dev.vercel.app/current/serverless/elasticsearch/elasticsearch-billing) - big note re: min VCUs, with detail explaining what the VCUs are for. [links here](https://www.elastic.co/pricing/serverless-search#what-are-the-minimum-compute-resource-vcus-on-elasticsearch-serverless)
could optionally add a note about free trials here.
[Elasticsearch get started](https://elastic-dot-co-docs-production-dng2tyfar-elastic-dev.vercel.app/current/se …

Add pricing info everywhere

---

serverless/pages/action-connectors.mdx

Contributes to https://github.com/elastic/security-docs/issues/5446. 
Adds a link in the serverless general docs to the new [CrowdStrike connector docs](https://www.elastic.co/guide/en/kibana/master/crowdstrike-action-type.html), which was recently added as part of Security's bidirectional integration with CrowdStrike.
- Click the [link below](https://github.com/elastic/docs-content/pull/46#issuecomment-2248624773), then click **View serverless docs** in any solution card. 
- Navigate to: **Project and management settings → Management → Connectors**.

Add link to new CrowdStrike connector

---

serverless/pages/elasticsearch-developer-tools.mdx

There was an extra > on the Dev Tools overview page in the Elasticsearch serverless docs at the end of the Grok Debugger bullet point and link. Fixed the output by removing the unnecessary character.

Fix dev tools overview page typo #150

---

serverless/nav/serverless-general.docnav.json
serverless/pages/cloud-regions.mdx
serverless/pages/get-started.mdx

Adds information about available cloud regions: [cloud regions](https://elastic-dot-co-docs-production-fxkx6n78d-elastic-dev.vercel.app/current/serverless/regions)
links to cloud region docs in ES project creation docs: [link](https://elastic-dot-co-docs-production-fxkx6n78d-elastic-dev.vercel.app/current/serverless/elasticsearch/get-started#create-project)
Added links in obs and sec project creation docs as well: 
https://github.com/elastic/observability-docs/pull/4093
https://github.com/elastic/security-docs/pull/5604

[Jul 31] Add cloud region info

---

.github/ISSUE_TEMPLATE/api-feedback.yaml

This PR creates an issue template that we can reference from the feedback link on https://www.elastic.co/docs/api/ pages.
It's based on the existing templates in this repo and on https://github.com/elastic/elasticsearch-specification/pull/2760/files

Add issue template for API feedback

---

.github/ISSUE_TEMPLATE/api-feedback.yaml

This PR fixes the following error that was occurring for the API feedback template: 
```
There is a problem with this template
body[1]: options must not include booleans. Please wrap values such as 'yes', and 'true' in quotes.
```
[Learn more about this error.](https://docs.github.com/communities/using-templates-to-encourage-useful-issues-and-pull-requests/common-validation-errors-when-creating-issue-forms#bodyi-options-must-not-include-booleans-please-wrap-values-such-as-yes-and-true-in-quotes)

Fix API feedback template

---

serverless/pages/explore-your-data-the-aggregations-api.mdx
serverless/pages/serverless-differences.mdx

Scripted metric aggregations are not available in Serverless. See also https://github.com/elastic/elasticsearch/pull/112161
Previews:
* [Differences page](https://elastic-dot-co-docs-production-oapkg1qid-elastic-dev.vercel.app/current/serverless/elasticsearch/differences)
* [Aggregations page](https://elastic-dot-co-docs-production-oapkg1qid-elastic-dev.vercel.app/current/serverless/elasticsearch/explore-your-data-aggregations)

Add scripted metrics to serverless differences

---

serverless/pages/manage-access-to-org.mdx

This PR must be merged after https://github.com/elastic/cloud/pull/130976
It adds a link from https://www.elastic.co/docs/current/serverless/general/manage-access-to-organization to a new page under https://www.elastic.co/guide/en/cloud/current/ec-organizations.html
https://elastic-dot-co-docs-production-ehjmlh7f2-elastic-dev.vercel.app/current/serverless/general/manage-access-to-organization
NOTE: The link within that preview will work after https://github.com/elastic/docs/pull/3048 is merged

[DOCS] Add link to Elastic Cloud SAML SSO details

---

.github/ISSUE_TEMPLATE/serverless-ux-bug-bash-issue.yaml

Adds a Serverless docs issue template for the UX bug bash.
Kaarina will delete template after bug bash.

Adds Serverless UX bug bash issue template for the Docs

---

serverless/pages/ingest-your-data-ingest-data-through-integrations-connector-client.mdx

This PR updates the [Connector clients](https://www.elastic.co/docs/current/serverless/elasticsearch/ingest-data-through-integrations-connector-client#run-from-source) page in the Serverless documentation.
[Serverless]: Connector Run from source procedure clarifications #68
[Connector clients](https://elastic-dot-co-docs-production-7ma6g91wi-elastic-dev.vercel.app/current/serverless/elasticsearch/ingest-data-through-integrations-connector-client)

Updates instructions for self-managed connectors

---

serverless/pages/manage-your-project.mdx

This PR adds 2 new options (maximum retention and default retention) to the Data retention project settings. These settings are valid for Security project only.
They're now visible on production.
Note: I'm documenting them where all other similar settings are documented. There is a page about Security project settings un the Security docs tree, which contains a simple link to the central project settings page, which I haven't touched to not scatter the information.
Closes: https://github.com/elastic/platform-docs-team/issues/491

Security projects new retention settings

---

serverless/pages/get-started.mdx

Closes https://github.com/elastic/docs-content/issues/85

Fix bugs in ES3 get started

---

serverless/pages/machine-learning.asciidoc
serverless/pages/manage-access-to-org-user-roles.asciidoc
serverless/pages/project-and-management-settings.asciidoc
serverless/pages/welcome-to-serverless.asciidoc

As Liam reported in [this thread](https://elastic.slack.com/archives/C05PP2LEC1X/p1730884542702359), some attributes were incorrect post migration of serverless docs from mdx to asciidoc. This PR updates the occurrences of the `{security}` attribute to `{elastic-sec}`.

Fixes security attribute

---

serverless/pages/ingest-your-data.asciidoc

This PR updates the [Ingest your data](https://www.elastic.co/guide/en/serverless/current/elasticsearch-ingest-your-data.html) page by adding the Elastic Open Web Crawler as an ingest method.
https://github.com/elastic/docs-content/issues/140

Adds Open Crawler as ingest method

---

serverless/pages/get-started.asciidoc

This PR updates the "Copy URL" section of the Elasticsearch -> Get Started page.
The related issue suggested the following wording:
- At the top of the Overview page, click on "View" next to "Connection details."
- Under the "Connection details" section, find the "Elasticsearch Endpoint" field.
- Copy the URL for the Elasticsearch Endpoint, as you will use this URL to send all Elasticsearch API requests.
In the tutorial, we guide users through the Getting Started page of the Serverless deployment, not the Overview page, so I adjusted the instructions accordingly. Additionally, I clarified that these instructions should be followed on the Getting Started page of the deployment.
https://github.com/elastic/docs-content/issues/86

Updates instructions on the Get started page

---

serverless/pages/project-settings.asciidoc

This is a follow-up PR to **Serverless updates** #185. 
It updates the wording for navigation to the Management page to align with the new [style guide guidelines](https://docs.elastic.dev/tech-writing-guidelines/ui-writing#referring-to-apps-and-pages).

Updates page navigation wording

---

serverless/pages/clients-dot-net-getting-started.asciidoc
serverless/pages/clients-go-getting-started.asciidoc
serverless/pages/clients-java-getting-started.asciidoc
serverless/pages/clients-nodejs-getting-started.asciidoc
serverless/pages/clients-php-getting-started.asciidoc
serverless/pages/clients-python-getting-started.asciidoc
serverless/pages/clients-ruby-getting-started.asciidoc
serverless/pages/clients.asciidoc

For Serverless GA: Fix #80 by adding banners to serverless client docs.
**Note:** These won't look right until https://github.com/elastic/docs-content/pull/196/ is merged to fix the `{es}` variable -- for example:
Before #196 is merged:
After #196 is merged:

Add banners noting that serverless clients are serverless only

---

serverless/index-serverless-elasticsearch.asciidoc
serverless/pages/what-is-elasticsearch-serverless.asciidoc

- 🔴  [Existing page](https://www.elastic.co/guide/en/serverless/current/what-is-elasticsearch-serverless.html)
- 🟢  [Preview new page](https://github.com/user-attachments/assets/b22bdc93-5a57-4a2f-9ddb-f3c10a90fe62)
Tries to simplify and clarify the CTAs for readers:
- Added reference to page rendering location
- Expanded Elasticsearch definition and serverless context
- Restructured "Get Started" section into cards
- Added "Learn More" section with cards
- Removed "How to" section and its subsections
- Added tip about checking main Elasticsearch docs for beginners

Update Elasticsearch Serverless landing page/overview

---

serverless/pages/action-connectors.asciidoc
serverless/pages/ingest-your-data-ingest-data-through-integrations-connector-client.asciidoc

This PR adds notes to the Connector clients and Connectors pages to provide users with more context about the content of these pages.
https://github.com/elastic/docs-content/issues/98
Connector [clients](https://docs-content_bk_215.docs-preview.app.elstc.co/guide/en/serverless/current/elasticsearch-ingest-data-through-integrations-connector-client.html)
[Connectors](https://docs-content_bk_215.docs-preview.app.elstc.co/guide/en/serverless/current/action-connectors.html)

Adds notes to Connector clients and Connectors page

---

serverless/index-serverless-general.asciidoc
serverless/index.asciidoc
serverless/pages/manage-billing-stop-project.asciidoc
serverless/pages/ml-nlp-auto-scale.asciidoc
serverless/pages/service-status.asciidoc
serverless/pages/welcome-to-serverless.asciidoc
serverless/pages/what-is-elasticsearch-serverless.asciidoc

Addresses part of https://github.com/elastic/security-docs/issues/6026 (from our serverless bug bash), mostly in the [general serverless](https://www.elastic.co/guide/en/serverless/current/intro.html) content set.  
Fixes serverless references + a few other slight nits I noticed while browsing. 
Attributes: 
```
:serverless-full:  Elastic Cloud Serverless
:serverless-short: Serverless
:es-serverless:    Elasticsearch Serverless
:es3:              {es-serverless}
:obs-serverless:   Elastic Observability Serverless
:sec-serverless:   Elastic Security Serverless
:serverless-docs:  https://docs.elastic.co/serverless
```

[Serverless] Fixes serverless references 

---

serverless/pages/serverless-differences.asciidoc

Closes https://github.com/elastic/platform-docs-team/issues/537#issuecomment-2506456164
☝️ Any more additions should come in new issue :)

Add index sizing guidelines

---

serverless/index-serverless-elasticsearch.asciidoc

a partial was removed from the overview page in https://github.com/elastic/docs-content/pull/191, leading to the page appearing empty. restoring the include statement
before 
after

fix overview page

---

serverless/pages/clients-java-getting-started.asciidoc

This PR updates the Java client docs to reflect the fact that there is no dedicated Java client for ES Serverless.

Update Java client docs (there's no serverless version)

---

serverless/pages/clients-go-getting-started.asciidoc

Recommend the Go stack client since the serverless one will be deprecated. 
Sister PR to https://github.com/elastic/docs-content/pull/242

Recommend Go stack client

---

serverless/pages/serverless-differences.asciidoc

In the current [Serverless docs](https://www.elastic.co/guide/en/serverless/current/elasticsearch-differences.html#elasticsearch-differences-serverless-feature-planned) we state that the following feature is planned:
> Authentication realms (native/SAML/OIDC/Kerberos/JWT)
This statement is not accurate.
Serverless projects will be accessible by customers only via Elastic Cloud users, that support external authentication providers via the BYOIDP Elastic Cloud functionality.
Direct configuration and use of other Elasticsearch realms generally used for Elastic Cloud Hosted deployments (like those mentioned in the list) will not be available in Serverless.

Remove authentication realms from Serverless planned features

---

deploy-manage/production-guidance/optimize-performance/search-speed.md
explore-analyze/aggregations.md
explore-analyze/query-filter.md
explore-analyze/query-filter/languages.md
manage-data/use-case-use-elasticsearch-to-manage-time-series-data.md
raw-migrated-files/docs-content/serverless/elasticsearch-search-your-data-the-search-api.md
raw-migrated-files/docs-content/serverless/elasticsearch-search-your-data.md
raw-migrated-files/elasticsearch/elasticsearch-reference/full-text-filter-tutorial.md
raw-migrated-files/elasticsearch/elasticsearch-reference/getting-started.md
raw-migrated-files/elasticsearch/elasticsearch-reference/search-analyze.md
raw-migrated-files/elasticsearch/elasticsearch-reference/search-with-elasticsearch.md
solutions/search/querying-for-search.md
solutions/search/rag/playground-query.md
solutions/search/ranking/learning-to-rank-search-usage.md
solutions/search/ranking/semantic-reranking.md
solutions/search/search-approaches.md
solutions/toc.yml
troubleshoot/elasticsearch/high-jvm-memory-pressure.md

Added new content to [search-approaches.md](https://github.com/elastic/docs-content/pull/291/files#diff-7f6dc9fb2c6e42aba2edee343783a6bbb4776cbae83d10a854708515765faac6)
- [👁️PREVIEW](https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/291/solutions/search/search-approaches.html)
Updated page name/links:
- `querying-for-search-searching-with-the-search-api.md` was renamed to `querying-for-search.md`. 
- all links have been updated (this section needs to be fleshed out with subpages in subsequent PRs and references checked for relevance)
- Also changed title from "Querying for search / searching with the search API" to "Query languages for search"
I tried using `docs-builder mv` to rename the `querying-for-search` file but I couldn't get it working and ran out of time, so just …

[Search] Add search approaches content, rename querying-for-search doc

---

.github/workflows/docs-build.yml
.github/workflows/docs-cleanup.yml
.github/workflows/docs-deploy.yml

Add fork-friendly PR preview deployment workflows.
Depends on https://github.com/elastic/docs-builder/pull/406

Add fork-friendly PR preview deployment workflows

---

explore-analyze/machine-learning/nlp.md
explore-analyze/machine-learning/nlp/ml-nlp-built-in-models.md
explore-analyze/machine-learning/nlp/ml-nlp-e5.md
explore-analyze/machine-learning/nlp/ml-nlp-elser.md
explore-analyze/machine-learning/nlp/ml-nlp-model-ref.md
explore-analyze/machine-learning/nlp/ml-nlp-rerank.md
explore-analyze/machine-learning/nlp/nlp-example.md

[E&A] Refines NLP model conceptual docs

---

manage-data/ingest/ingesting-data-from-applications/ingest-data-from-beats-to-elasticsearch-service-with-logstash-as-proxy.md
manage-data/ingest/ingesting-data-from-applications/ingest-data-from-relational-database-into-elasticsearch-service.md
manage-data/ingest/ingesting-data-from-applications/ingest-data-with-nodejs-on-elasticsearch-service.md
manage-data/ingest/ingesting-data-from-applications/ingest-data-with-python-on-elasticsearch-service.md
manage-data/ingest/ingesting-data-from-applications/ingest-logs-from-nodejs-web-application-using-filebeat.md
manage-data/ingest/ingesting-data-from-applications/ingest-logs-from-python-application-using-filebeat.md

This merges the ESS and ECE versions of the "Ingest data from your application" guides. 
The main difference is in the initial steps, which were to log into ESS / ECE. I've replaced with with tabs:
I've also removed the list of steps/links that were at the top of the longer guides, since the new docs system shows a document ToC at the top right.
**NOTE:** The above the only significant changes, so please don't read through the full set of guides. :-)
The guides:
- [Ingest data with Node.js](https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/343/manage-data/ingest/ingesting-data-from-applications/ingest-data-with-nodejs-on-elasticsearch-service.html)
- [Ingest data with Python on Elasticsearch Service](https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/343/manage-data/ …

[Manage data] Add 'Ingesting data from Applications' tutorials

---

solutions/search/inference-api/alibabacloud-ai-search-inference-integration.md
solutions/search/inference-api/amazon-bedrock-inference-integration.md
solutions/search/inference-api/anthropic-inference-integration.md
solutions/search/inference-api/azure-ai-studio-inference-integration.md
solutions/search/inference-api/azure-openai-inference-integration.md
solutions/search/inference-api/chat-completion-inference-api.md
solutions/search/inference-api/cohere-inference-integration.md
solutions/search/inference-api/elastic-inference-service-eis.md
solutions/search/inference-api/elasticsearch-inference-integration.md
solutions/search/inference-api/elser-inference-integration.md
solutions/search/inference-api/google-ai-studio-inference-integration.md
solutions/search/inference-api/google-vertex-ai-inference-integration.md
solutions/search/inference-api/huggingface-inference-integration.md
solutions/search/inference-api/jinaai-inference-integration.md
solutions/search/inference-api/mistral-inference-integration.md
solutions/search/inference-api/openai-inference-integration.md
solutions/search/inference-api/watsonx-inference-integration.md

Add navigation_title to inference API integration pages, and fix a capitalization typo.

Add navigation_title to inference pages

---

explore-analyze/index.md
explore-analyze/machine-learning/anomaly-detection/ml-ad-run-jobs.md
explore-analyze/machine-learning/anomaly-detection/ml-ad-troubleshooting.md
explore-analyze/machine-learning/anomaly-detection/ml-configuring-populations.md
explore-analyze/machine-learning/anomaly-detection/ml-getting-started.md
explore-analyze/machine-learning/anomaly-detection/ml-reverting-model-snapshot.md
explore-analyze/machine-learning/data-frame-analytics/ml-dfa-classification.md
explore-analyze/machine-learning/data-frame-analytics/ml-dfa-finding-outliers.md
explore-analyze/machine-learning/data-frame-analytics/ml-dfa-regression.md

[E&A] Amends E&A overview.

---

solutions/search/inference-api/chat-completion-inference-api.md
solutions/search/inference-api/jinaai-inference-integration.md

Add missing callouts to two Inference API subpages

Add missing callouts

---

solutions/search/retrievers-examples.md

Replace links and remove comments in retrievers-examples.md.

Replace links and remove comments

---

deploy-manage/users-roles/cloud-organization/configure-saml-authentication.md
troubleshoot/deployments/elastic-cloud/sso.md
troubleshoot/toc.yml

Move SSO troubleshooting tips from Deploy section to Troubleshoot section.
For now, adding under troubleshoot > deployments, but forever home may change.

Move Troubleshooting SSO content

---

explore-analyze/index.md

See https://github.com/elastic/docs-projects/issues/412#issuecomment-2663899798
I moved the content of the accessibility page into the index, but missed to bring the mapped URL along with it. This PR corrects it.

Add missing mapped URL for explore and analyze

---

deploy-manage/deploy/cloud-enterprise.md
deploy-manage/deploy/cloud-enterprise/ece-regional-deployment-aliases.md
deploy-manage/deploy/cloud-on-k8s.md
deploy-manage/deploy/cloud-on-k8s/k8s-openshift-agent.md
deploy-manage/deploy/elastic-cloud/add-plugins-extensions.md
deploy-manage/deploy/elastic-cloud/cloud-hosted.md
deploy-manage/deploy/elastic-cloud/ech-getting-started.md
deploy-manage/deploy/elastic-cloud/serverless.md
deploy-manage/deploy/self-managed/plugins.md
deploy-manage/index.md
deploy-manage/reference-architectures.md
explore-analyze/machine-learning/anomaly-detection/ml-getting-started.md
get-started/index.md
get-started/the-stack.md
manage-data/ingest/transform-enrich/ingest-pipelines.md
raw-migrated-files/cloud/cloud-heroku/ech-adding-plugins.md
raw-migrated-files/observability-docs/observability/observability-get-started.md
raw-migrated-files/stack-docs/elastic-stack/overview.md
solutions/observability/apps/configure-real-user-monitoring-rum.md
solutions/observability/apps/tutorial-monitor-java-application.md
solutions/observability/cloud/monitor-amazon-cloud-compute-ec2.md
solutions/observability/cloud/monitor-amazon-kinesis-data-streams.md
solutions/observability/cloud/monitor-amazon-simple-queue-service-sqs.md
solutions/observability/cloud/monitor-amazon-simple-storage-service-s3.md
solutions/observability/get-started.md
solutions/search/site-or-app/search-ui.md
solutions/security.md
troubleshoot/ingest/fleet/frequently-asked-questions.md

Replace links to `index.html` paths in the AsciiDoc docs (for example, https://www.elastic.co/guide/en/beats/heartbeat/current/index.html).

Handle `index.html` AsciiDoc links

---

solutions/observability/apps/transaction-sampling.md

This PR moves the changes introduced in https://github.com/elastic/observability-docs/pull/4814 by @carsonip to our new 9.0 docs.

apm: change default sampling.tail.storage_limit

---

deploy-manage/deploy/cloud-on-k8s.md

Minor change about ECK supported versions.
I have also added this sentence that I had removed during the migration from the original doc and I had it pending on my `to-do` list:
> Alpha, beta, and stable API versions follow the same [conventions used by Kubernetes](https://kubernetes.io/docs/concepts/overview/kubernetes-api/#api-versioning).

porting cloud-on-k8s PR #8489

---

deploy-manage/deploy/cloud-enterprise/configure-host-rhel-cloud.md
deploy-manage/deploy/cloud-enterprise/configure-host-rhel-onprem.md
deploy-manage/deploy/cloud-enterprise/migrate-ece-to-podman-hosts.md

To prevent automatic Podman major version updates, configure the Podman version to be locked while still allowing minor and patch updates.

Lock Podman major version

---

reference/ingestion-tools/fleet/otel-agent-transform.md
reference/toc.yml

I revisited the IA inventory and found [one page](https://github.com/elastic/ingest-docs/blob/do-not-delete_legacy-docs/docs/en/ingest-management/elastic-agent/otel-agent-transform.asciidoc) that existed on `main` in elastic/ingest-docs, but never made it to `current`.

Add missing Fleet page

---

deploy-manage/upgrade/prepare-to-upgrade.md

Contributes to https://github.com/elastic/docs-projects/issues/454 by adding the Anomaly detection results migration section to the Prepare to upgrade page in the upgrade guide.
Preview: [Prepare to upgrade](https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/625/deploy-manage/upgrade/prepare-to-upgrade)

Anomaly detection results migration

---

deploy-manage/deploy/elastic-cloud/add-plugins-extensions.md
deploy-manage/tools/snapshot-and-restore.md
deploy-manage/tools/snapshot-and-restore/access-isolation-for-found-snapshots-repository.md
deploy-manage/tools/snapshot-and-restore/azure-repository.md
deploy-manage/tools/snapshot-and-restore/azure-storage-repository.md
deploy-manage/tools/snapshot-and-restore/cloud-enterprise.md
deploy-manage/tools/snapshot-and-restore/cloud-on-k8s.md
deploy-manage/tools/snapshot-and-restore/ec-aws-custom-repository.md
deploy-manage/tools/snapshot-and-restore/ec-azure-snapshotting.md
deploy-manage/tools/snapshot-and-restore/ec-gcs-snapshotting.md
deploy-manage/tools/snapshot-and-restore/ece-restore-across-clusters.md
deploy-manage/tools/snapshot-and-restore/ece-restore-snapshots-containing-searchable-snapshots-indices-across-clusters.md
deploy-manage/tools/snapshot-and-restore/ece-restore-snapshots-into-existing-deployment.md
deploy-manage/tools/snapshot-and-restore/ece-restore-snapshots-into-new-deployment.md
deploy-manage/tools/snapshot-and-restore/elastic-cloud-hosted.md
deploy-manage/tools/snapshot-and-restore/google-cloud-storage-gcs-repository.md
deploy-manage/tools/snapshot-and-restore/google-cloud-storage-repository.md
deploy-manage/tools/snapshot-and-restore/minio-on-premise-repository.md
deploy-manage/tools/snapshot-and-restore/read-only-url-repository.md
deploy-manage/tools/snapshot-and-restore/repository-isolation-on-aws-gcp.md
deploy-manage/tools/snapshot-and-restore/s3-repository.md
deploy-manage/tools/snapshot-and-restore/self-managed.md
deploy-manage/tools/snapshot-and-restore/shared-file-system-repository.md
deploy-manage/tools/snapshot-and-restore/source-only-repository.md
deploy-manage/uninstall/delete-a-cloud-deployment.md
deploy-manage/uninstall/uninstall-elastic-cloud-enterprise.md
deploy-manage/uninstall/uninstall-elastic-cloud-on-kubernetes.md

This PR adds the missing mapped URLs listed [in this sheet](https://docs.google.com/spreadsheets/d/150kky51hHUIec6K6EZosZOWVSzAnsGeVd4M4-w5jAKE/edit?gid=0#gid=0).

Adds missing mapped URLs

---

reference/ingestion-tools/fleet/agent-command-reference.md

This is a forward fit of https://github.com/elastic/ingest-docs/pull/1668 into the 9.0 docs.

Remove 'non-interactive-mode' option for Agent 'enroll' command

---

solutions/security/cloud/benchmarks.md
solutions/security/cloud/cspm-frequently-asked-questions-faq.md
solutions/security/dashboards/cloud-native-vulnerability-management-dashboard.md
solutions/security/dashboards/cloud-security-posture-dashboard.md

Does it make sense to redirect the AsciiDoc URLs I added in this PR to the v3 files they were added to? I _think_ it might be that there are some AsciiDoc pages that are near duplicates, but I could be wrong about that.

[security] Add missing mapped pages

---

solutions/search/inference-api/chat-completion-inference-api.md
solutions/search/inference-api/elastic-inference-service-eis.md
solutions/search/inference-api/openai-inference-integration.md
solutions/search/semantic-search/cohere-es.md

Relates to https://github.com/elastic/docs-content/issues/339
This PR copies the changes that were originally done against the asciidoc files in https://github.com/elastic/elasticsearch/pull/121078 and applies them to the files in their new location in docs-content.
NOTE: Three of the files affected by this PR will ultimately be removed since they're duplicates of info we're adding to the OpenAPI docs per https://github.com/elastic/elasticsearch-specification/issues/3821.

Fix references to _unified inference API

---

explore-analyze/alerts-cases/alerts/rule-action-variables.md
explore-analyze/machine-learning/data-frame-analytics/ml-trained-models.md
explore-analyze/query-filter/languages/sql-functions-datetime.md
explore-analyze/scripting/modules-scripting-expression.md
explore-analyze/visualize/custom-visualizations-with-vega.md
explore-analyze/visualize/maps/maps-clean-data.md

In the migration tool, external URLs that contained `.html` were incorrectly modified to use `.md`.  
To (attempt) to fix these links:
1. I ran a script to find URLs that started with `http` (i.e. is not an internal or cross-repo link) and included `.md` somewhere in the URL.
2. Then I ran all the resulting URLs through an external link-checker.
i. If I got a [`200` status code](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/200) back, I didn't do anything to the link.
ii. If I got a [`404` status code](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404) back, I swapped out the `.md` with `.html`.
3. I reran the link-checker to make sure all the updated links were now returning `200`.

[explore and analyze] Fix external links

---

solutions/security/advanced-entity-analytics/anomaly-detection.md
solutions/security/advanced-entity-analytics/behavioral-detection-use-cases.md
solutions/security/dashboards/entity-analytics-dashboard.md

Updates lingering refs to the old `prebuilt-jobs.md` file. These refs now point to the new `prebuilt-anomaly-detection-jobs.md` file that was added in https://github.com/elastic/docs-content/pull/695.
Previews:
- [Anomaly detection](https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/698/solutions/security/advanced-entity-analytics/anomaly-detection)
- [Behavioral detection use cases](https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/698/solutions/security/advanced-entity-analytics/behavioral-detection-use-cases)
- [Entity Analytics dashboard](https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/698/solutions/security/dashboards/entity-analytics-dashboard)

Update outdated refs to the `prebuilt-jobs.md` file

---

deploy-manage/license/manage-your-license-in-eck.md

`shell script` is not a valid code block argument and will start failing when https://github.com/elastic/docs-builder/pull/699 is merged

Fix codeblock

---

reference/data-analysis/machine-learning/ootb-ml-jobs-siem.md

Related to https://github.com/elastic/stack-docs/pull/2987 and https://github.com/elastic/search-docs-team/issues/269
This PR updates the steps to add & configure dashboard for the ML`Security: Host` OOTB module.
- https://github.com/elastic/security-team/issues/10414

Update steps to configure dashboard for Security: Host module

---

deploy-manage/autoscaling/trained-model-autoscaling.md

Related to https://github.com/elastic/ml-team/issues/1500
This PR adds a blurb about how we calculate VCUs for ML:
- Trained Models are mostly based on vCPU consumed, 1 allocation * 1 thread = 1 vCPU = 8 VCU
- Jobs are mostly based on memory consumed, 1 GB = 1 VCU

[D&M] Explains pricing on Serverless for adaptive resources

---

deploy-manage/deploy/elastic-cloud/add-plugins-extensions.md

Update Plugin Management link connected to [this pull request](https://github.com/elastic/elasticsearch/pull/124578).

Update Plugin Management link

---

reference/ingestion-tools/fleet/install-elastic-agents.md

This is a forward fit of https://github.com/elastic/ingest-docs/pull/1731 into the 9.0 docs. It updates the [Install Elastic Agents](https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/785/reference/ingestion-tools/fleet/install-elastic-agents) page with the following note.
---

[Fleet] Add tip for dynamic inputs

---

deploy-manage/deploy/elastic-cloud/edit-stack-settings.md

Update link to point to the new Elasticsearch reference content, based on [this issue](https://github.com/elastic/docs-content/issues/689). For [this pull request](https://github.com/elastic/elasticsearch/pull/125000)

Update link to Elasticsearch reference content

---

explore-analyze/machine-learning/nlp/ml-nlp-elser.md

Related issue: https://github.com/elastic/search-docs-team/issues/258
This PR changes the `inference-id` and `model-id` of the example API call for downloading ELSER to be in sync with the Semantic search with ELSER tutorial.

Fixing inference-id and harmonizing model-id

---

solutions/search/semantic-search.md

@Mikep86's great blog needs findability in docs

[Search] Add link to semantic_text GA blog

---

reference/ingestion-tools/fleet/upgrade-elastic-agent.md

Redo of https://github.com/elastic/docs-content/pull/773
This updates the Elastic Agent upgrade steps for 9.0. It seems the only change required is to set the hard-coded versions to use the new `{{stack-version}}` variable.
The screen captures all show 8.x versions, but I think that makes sense for now since we don't have 9.x versions to upgrade to.
See: [Preview page](https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/808/reference/ingestion-tools/fleet/upgrade-elastic-agent)
Closes: https://github.com/elastic/ingest-docs/issues/1730

Update Fleet & Agent 'Upgrade' page, Take 2

---

deploy-manage/upgrade/deployment-or-cluster/upgrade-on-ece.md
deploy-manage/upgrade/deployment-or-cluster/upgrade-on-ech.md
deploy-manage/upgrade/deployment-or-cluster/upgrade-on-eck.md

Contributes to https://github.com/elastic/docs-projects/issues/247 and https://github.com/elastic/docs-projects/issues/355.
Previews: 
- [Upgrade on ECE](https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/812/deploy-manage/upgrade/deployment-or-cluster/upgrade-on-ece)
- [Upgrade on ECK](https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/812/deploy-manage/upgrade/deployment-or-cluster/upgrade-on-eck)

[Upgrade 9.0] Adds ECE/ECK upgrade topics

---

explore-analyze/query-filter/tools/console.md
solutions/search/querying-for-search.md
solutions/search/serverless-elasticsearch-get-started.md

The Kibana doc link service currently links to https://www.elastic.co/guide/en/serverless/current/devtools-run-api-requests-in-the-console.html, which seems to be identical to https://www.elastic.co/guide/en/kibana/current/console-kibana.html.
This PR therefore adds the former URL to the list of mapped pages for https://docs-v3-preview.elastic.dev/elastic/docs-content/tree/main/explore-analyze/query-filter/tools/console and updates some other links to that page.

Fix links for Console

---

solutions/search/vector.md

Apparently people say "numbers" not "bumbers" nowadays. My how times have changed. 👴

Fix typo in vector.md

---

solutions/observability/infra-and-hosts/universal-profiling.md

A quick fix for a link that was still using old Asciidoc styling.

Fix asciidoc-style link

---

troubleshoot/kibana.md
troubleshoot/kibana/access.md
troubleshoot/kibana/alerts.md
troubleshoot/kibana/capturing-diagnostics.md
troubleshoot/kibana/error-server-not-ready.md
troubleshoot/kibana/graph.md
troubleshoot/kibana/maps.md
troubleshoot/kibana/migration-failures.md
troubleshoot/kibana/monitoring.md
troubleshoot/kibana/reporting.md
troubleshoot/kibana/task-manager.md
troubleshoot/kibana/trace-elasticsearch-query-to-the-origin-in-kibana.md
troubleshoot/kibana/using-kibana-server-logs.md

Adds `applies_to` tags to the **Troubleshoot > Kibana** section.
Preview: [Kibana](https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/910/troubleshoot/kibana)

Add applies tags to Troubleshoot > Kibana

---

explore-analyze/query-filter/languages/esql-getting-started.md
explore-analyze/query-filter/languages/esql.md
solutions/search/esql-for-search.md
solutions/search/querying-for-search.md
solutions/toc.yml

Painful manual IA re-mapping and syntax porting to v3 based on https://github.com/elastic/elasticsearch/pull/125580

Add 9.x ESQL for Search landing page

---

deploy-manage/license.md
deploy-manage/monitor.md

`ech` is not a valid `applies_to` value but I accidentally used it. replacing with `ess`
issue re: linting for these is [here](https://github.com/elastic/docs-builder/issues/610)
issue re: accepting `ech` is [here](https://github.com/elastic/docs-builder/issues/563)
thanks for the catch @stefnestor

more applies_to cleanup

---

deploy-manage/deploy/self-managed.md
explore-analyze/query-filter/tools/grok-debugger.md
explore-analyze/query-filter/tools/search-profiler.md
explore-analyze/scripting/painless-lab.md
reference/observability/elastic-entity-model.md
reference/observability/index.md
release-notes/intro/index.md
solutions/observability/apps/inventory.md
troubleshoot/elasticsearch/troubleshooting-searches.md

Add missing mapped pages for redirect purposes.

[docs] Add missing mapped pages

---

solutions/security/detect-and-alert/manage-detection-alerts.md

Fixes https://github.com/elastic/docs-content/issues/321.
The following UI changes were made to the Alerts page in 9.1 and Serverless:
- Inline actions for the visualizations of alerts were moved into the more actions menu to align the visualizations' design with Lens'.  
- Copy for the actions were tweaked to align them with Discover's. For example, **Filter In** was changed to **Filter for**.
Since these modifications were so visually minor, I decided against updating screenshots of the Alerts tables. In the docs about using inline actions from the alerts page I removed examples that were only applicable to 9.0 and not Serverless. Those docs link off to our main docs on inline actions (which apply more broadly across the Security app), so the duplicate info isn't needed. 
[Manage …

[Serverless] Standardize actions in Alerts KPI visualizations and update actions copy

---

deploy-manage/upgrade/prepare-to-upgrade.md

Call out specifically to look for cluster stability, performance, and snapshot repository bugs.
Relates https://github.com/elastic/stack-docs/pull/3009

Expand guidance on testing an upgrade

---

deploy-manage/security/aws-privatelink-traffic-filters.md
deploy-manage/security/encrypt-deployment-with-customer-managed-encryption-key.md

This PR brings changes that were made to asciidoc docs for ECH to the new docs:

Port ECH asciidoc changes to new docs

---

deploy-manage/deploy/self-managed/_snippets/start-local.md

We want to refer to the README as the source of truth, so keeping this page as lean as possible
https://github.com/elastic/search-team/issues/9677#issuecomment-2765378363

Simplify start-local.md

---

reference/index.md

Hello!
While I was working on making use of the front matter to show the user there's a previous version available, I've found an incorrect character being used to define the mapped page.
This change fixes things here!

Fix symbol being used on mapped_pages front matter

---

manage-data/data-store/data-streams/logs-data-stream.md

Update header for logsdb upgrading notes.

Fix notes header for logsdb upgrading

---

deploy-manage/monitor/stack-monitoring/ece-ech-stack-monitoring.md
raw-migrated-files/cloud/cloud/ec-monitoring-setup.md

See https://github.com/elastic/cloud/pull/139451
Also edited a raw file just in case it's still going to be used somewhere else

Reproduce asciidoc updates to logging and monitoring with sizing reco for ES instances

---

deploy-manage/security/self-setup.md
redirects.yml

[This tutorial](https://github.com/elastic/docs-content/blob/main/raw-migrated-files/stack-docs/elastic-stack/install-stack-demo-secure.md) is hidden while we figure out what content is still needed from it (most of it is a duplicate, and it's only relevant to self-managed)
so I have mapped the page to the explanation of how to set up security in a self-managed environment and added a redirect.

Add mapping and redirect for hidden security tutorial

---

deploy-manage/users-roles/cluster-or-deployment-auth/built-in-roles.md

[D&M] Fixes typo on built-in role page

---

serverless/pages/custom-roles.asciidoc

in prod, the custom roles doc is empty. 
https://www.elastic.co/guide/en/serverless/current/custom-roles.html
the feature flag is [properly set](https://github.com/elastic/docs/blob/master/shared/versions/stack/master.asciidoc#L82) as far as I can tell
it works locally with no changes (also with this change)
given that we will be on this system for only approx 24 more hours, I'm just killing the flag logic so the content shows up

remove feature flag due to rendering issue

---

solutions/security/advanced-entity-analytics/entity-risk-scoring.md

Contributes to https://github.com/elastic/docs-content/issues/835.
Preview: [Entity risk scoring](https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/1073/solutions/security/advanced-entity-analytics/entity-risk-scoring)

Risk scoring calculation improvements

---

solutions/security/configure-elastic-defend/configure-data-volume-for-elastic-endpoint.md

Contributes to https://github.com/elastic/security-docs/issues/5771.
Adds Serverless applies tag to the Configure data volume for Elastic Endpoint page. Confirmed with Dan Ferullo that this change is being released in Serverless at the same time 8.18 is released.
Preview: [Configure data volume](https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/1074/solutions/security/configure-elastic-defend/configure-data-volume-for-elastic-endpoint)

Adds Serverless badge to Configure data volume for Elastic Endpoint page

---

deploy-manage/autoscaling/autoscaling-in-ece-and-ech.md

fix tables with a false header row + also empty columns
👎 old ☹️ 
✨ new 😍

fix tables

---

release-notes/elastic-cloud-serverless/known-issues.md
release-notes/elastic-security/known-issues.md

Addresses part of https://github.com/elastic/docs-content/issues/1094.

Adds a Security known issue for serverless and 9.0.0

---

explore-analyze/query-filter/languages/esql-getting-started.md
explore-analyze/query-filter/languages/esql-kibana.md

Connected to: https://github.com/elastic/docs-content/pull/1095
Update links to ESQL reference docs following up on https://github.com/elastic/elasticsearch/pull/126279 that splits the Functions and Operators page into separate pages, one for each group of similar functions and one for the operators.
Based on https://github.com/elastic/docs-content/issues/1072

Update links to ESQL reference docs

---

get-started/versioning-availability.md

as discussed, adding a link to the top of /guide for people to access our old documentation system

add guide link

---

deploy-manage/deploy/cloud-on-k8s/required-rbac-permissions.md
deploy-manage/deploy/elastic-cloud/azure-native-isv-service.md
reference/fleet/add_kubernetes_metadata-processor.md
reference/fleet/add_nomad_metadata-processor.md
reference/fleet/elastic-agent-ssl-configuration.md
reference/fleet/elasticsearch-output.md
reference/fleet/es-output-settings.md
reference/fleet/kafka-output-settings.md
reference/fleet/kafka-output.md
reference/fleet/logstash-output.md
solutions/observability/apm/data-streams.md
solutions/observability/synthetics/configure-lightweight-monitors.md

Fixes poorly migrated complex tables, for example tables that include:
* `<br>` inside inline `code` ([example](https://staging-website.elastic.co/docs/deploy-manage/deploy/cloud-on-k8s/required-rbac-permissions#k8s-eck-permissions-using))
* Code blocks inside table cells ([example](https://staging-website.elastic.co/docs/reference/fleet/elasticsearch-output#output-elasticsearch-hosts-setting))
* Dropdowns inside table cells ([example](https://staging-website.elastic.co/docs/reference/fleet/add_kubernetes_metadata-processor#_configuration_settings_7))
* Admonitions inside table cells ([example](https://staging-website.elastic.co/docs/reference/fleet/elasticsearch-output#output-elasticsearch-hosts-setting))
For the most part, I replaced tables that contain these elements with definition …

Fix poorly migrated complex tables

---

release-notes/elastic-security/breaking-changes.md
release-notes/elastic-security/deprecations.md
release-notes/elastic-security/index.md

Updates templates for the Security release notes to enforce the correct version format in section headers.
Related issue: https://github.com/elastic/docs-content/issues/1152

[Security] Update release notes ID format for automated URL generation

---

reference/fleet/remote-elasticsearch-output.md

Closes https://github.com/elastic/kibana/issues/208946
This PR updates the documentation about remote Elasticsearch outputs with:
- a mention of the feature to sync uninstalled integrations
- a new troubleshooting section

[Add] Add integration syncing troubleshooting section to remote ES output doc

---

deploy-manage/cloud-organization/service-status.md

https://elasticco.atlassian.net/browse/SRERE-882
As we no longer use cloud-status, updating the references to point to status.elastic.co

Remove `cloud-status` reference

---

solutions/search/ranking/semantic-reranking.md

Updating Semantic_reranker to include preconfigured endpoint as part of the GA process.

Updating documentation for semantic_reranking

---

.github/workflows/add-new-team-label.yml
.github/workflows/add-to-board.yml
.github/workflows/add-triage-label.yml

Add issue automation

---

solutions/observability/apm/get-started-apm-server-binary.md

[Docs ](https://www.elastic.co/docs/solutions/observability/apm/get-started-apm-server-binary#apm-setup-repositories)are showing 9.0.0beta1 not available messages. This PR updates the docs to manually add the steps and update versions.

Fix the YUM and APT steps in APM server binary getting started

---

reference/fleet/fleet-api-docs.md

Updates our API examples with recipes for fetching more than 10k agents with `/api/fleet/agents`.
Docs preview: [List all Elastic Agents](https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/1193/reference/fleet/fleet-api-docs#list-agents-api) section
Closes: https://github.com/elastic/ingest-docs/issues/1726
@jen-huang Sorry this one took me ages to get to. Please let me know whatever I may have missed. By the way, I left the examples as curl since the others on that page are in the same format.

[Fleet] Add examples for 10k+ agents API fetch

---

manage-data/ingest/transform-enrich.md

This updates [Transform and enrich data](https://www.elastic.co/docs/manage-data/ingest/transform-enrich), which is part of the "manage data" > "Ingestion" section, with a sentence and link to the "Transforms" pages, all about pivoting existing indices. 
---

Add link from 'manage data' to Transforms page

---

deploy-manage/security/supported-ssltls-versions-by-jdk-version.md

Elasticsearch 9.0 and later require JDK21
This changes the docs regarding TLS versions to reflect the behaviour on modern JDKs.
Relates: 
- https://github.com/elastic/elasticsearch/pull/121731 
- https://github.com/elastic/elasticsearch/pull/121732

Update TLS versions for JDK21

---

explore-analyze/query-filter/languages/esql-cross-clusters.md
explore-analyze/query-filter/languages/esql-elastic-security.md
explore-analyze/query-filter/languages/esql-examples.md
explore-analyze/query-filter/languages/esql-getting-started.md
explore-analyze/query-filter/languages/esql-kibana.md
explore-analyze/query-filter/languages/esql-multi-index.md
explore-analyze/query-filter/languages/esql-multi.md
explore-analyze/query-filter/languages/esql-rest.md
explore-analyze/query-filter/languages/esql-where.md
explore-analyze/query-filter/languages/esql.md
explore-analyze/toc.yml

Mainly cosmetic, but should improve the UX for users landing in **Explore & Analyze** for ESQL:
Rough summary:
- removed gerund forms ("using", "getting") from all titles
- shortened, edited navigation titles where necessary
- added two new parent pages (esql-where.md, esql-multi.md) for logical grouping
- updated toc.yml to reflect new hierarchical structure
- marked cross-clusters feature as unavailable for serverless
- expanded esql landing page with clearer structure and examples
- reorganized reference documentation into visual groups
- added section on user interfaces with programmatic vs interactive options
- added more cross-links between related docs
- improved consistency in capitalization and terminology

[E&A] Spruce up ESQL landing page

---

deploy-manage/tools/snapshot-and-restore/read-only-url-repository.md
deploy-manage/tools/snapshot-and-restore/shared-file-system-repository.md
deploy-manage/tools/snapshot-and-restore/source-only-repository.md
explore-analyze/query-filter/aggregations.md

Re-add and fix superscripts in the documentation.
Based on: https://github.com/elastic/docs-content/issues/1170

Fix superscripts in documentation

---

solutions/search/using-resolve-cluster-endpoint-before-cross-cluster-search.md

https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/1223/solutions/search/using-resolve-cluster-endpoint-before-cross-cluster-search
- fix applies to
- fix heading
- add link to API doc
- minor language cleanup

Update CCS subpage

---

solutions/search/vector/knn.md

Reverts elastic/docs-content#995
Sorry @benwtrent we need to wait for 9.1.0 to merge this, I mistakenly thought we could flag things more granularly in the API reference, and then promptly forgot about this PR. We will probably soon have a current/next system in the new docs to simplify this process.

Revert "Make rescore_vector generally available"

---

release-notes/elastic-cloud-serverless/index.md

Updates the April 24, 2025 Serverless changelog

---

deploy-manage/deploy/cloud-enterprise/ece-wildcard-dns.md

Adds `ip.es.io` disclaimer to warning and security@elastic.co for reporting security issues.

Adds Wildcard DNS record disclaimers

---

solutions/observability/apm/data-stream-routing.md
solutions/toc.yml

This PR adds a new page under APM OTel to describe data stream routing.
Closes https://github.com/elastic/apm-server/issues/16204.

Add OTel data stream routing page

---

cloud-account/add-a-login-method.md
cloud-account/change-your-password.md
cloud-account/index.md
cloud-account/join-or-leave-an-organization.md
cloud-account/multifactor-authentication.md
cloud-account/update-your-email-address.md
manage-data/migrate/migrate-from-a-self-managed-cluster-with-a-self-signed-certificate-using-remote-reindex.md
manage-data/migrate/migrate-internal-indices.md
solutions/observability/incident-management/create-an-uptime-duration-anomaly-rule.md
solutions/search.md

replaces invalid `applies` and `hosted` tags with valid `applies_to` and `ess` tags
before: https://www.elastic.co/docs/cloud-account/join-or-leave-an-organization
after: https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/1263/cloud-account/join-or-leave-an-organization
part of https://github.com/elastic/docs-content/issues/1197

fix applies tags

---

deploy-manage/users-roles/cluster-or-deployment-auth/active-directory.md
deploy-manage/users-roles/cluster-or-deployment-auth/ldap.md
deploy-manage/users-roles/cluster-or-deployment-auth/pki.md

This fixes the `applies_to` tagging for [LDAP user authentication](https://www.elastic.co/docs/deploy-manage/users-roles/cluster-or-deployment-auth/ldap) and [Active Directory user authentication](https://www.elastic.co/docs/deploy-manage/users-roles/cluster-or-deployment-auth/active-directory) to apply to ECE only (rather than ECE, hosted, self, and K8s).
Added the [PKI page](https://www.elastic.co/docs/deploy-manage/users-roles/cluster-or-deployment-auth/pki) too.

Remove `ess` apply labels from LDAP, PKI, and AD authentication pages

---

manage-data/ingest/transform-enrich/ingest-pipelines-serverless.md
manage-data/ingest/transform-enrich/ingest-pipelines.md

While fixing URLS in Kibana doc link service, I saw https://www.elastic.co/docs/manage-data/ingest/transform-enrich/ingest-pipelines-serverless and https://www.elastic.co/docs/manage-data/ingest/transform-enrich/ingest-pipelines seem to have incorrect applies_to frontmatter.  This PR fixes the frontmatter to match the titles. If they're later consolidated into a single page, the frontmatter can be updated again.

Update frontmatter in ingest-pipelines sibling pages

---

manage-data/data-store/data-streams/modify-data-stream.md

Add documentation for the `/_data_stream/_modify` API

Add doc for the modify data stream API

---

solutions/observability/apm/data-stream-routing.md

Apply suggestion from https://github.com/elastic/docs-content/pull/1260#discussion_r2059968181.

Fix data stream routing wording

---

reference/fleet/install-standalone-elastic-agent.md

Fixes the tabs on the standalone Elastic Agent page, and also changes "AMD" to "Intel".
Closes: https://github.com/elastic/ingest-docs/issues/1785
---

[Fleet] Fix standalone Elastic Agent install tabs

---

reference/fleet/install-standalone-elastic-agent.md

In the Fleet UI, the install steps for macOS now default to aarch64 rather than x86_64.
---
Closes: https://github.com/elastic/ingest-docs/issues/1649

[Fleet] Update agent install steps for macOS aarch64

---

reference/fleet/remote-elasticsearch-output.md

This adds a note to the Fleet "Remote Elasticsearch Output" page indicating that warning about unhealthy state can be ignored in cases where Fleet Server can't connect to the remote cluster used only for agent data.
Please see: [Docs preview](https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/1307/reference/fleet/remote-elasticsearch-output#configuration)
Closes: https://github.com/elastic/docs-content/issues/1201
---

[Fleet] unhealthy remote ES warning can be ignored

---

solutions/security/dashboards/entity-analytics-dashboard.md

Contributes to https://github.com/elastic/docs-content/issues/1225 by mentioning service risk in the intro paragraph on the Entity Analytics dashboard page. 
Preview: [Entity Analytics dashboard](https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/1323/solutions/security/dashboards/entity-analytics-dashboard)
8.18 PR: https://github.com/elastic/security-docs/pull/6803

Mention service risk on Entity Analytics dashboard page

---

redirects.yml

Redirect for Serverless version of 'ingest pipelines' page deleted by https://github.com/elastic/docs-content/pull/1329

Add redirect for deleted 'ingest pipelines' page

---

solutions/security/get-started/_snippets/agentless-integrations-faq.md
solutions/security/get-started/agentless-integrations-faq.md
troubleshoot/security.md
troubleshoot/security/agentless-integrations.md
troubleshoot/toc.yml

Fixes a broken link to https://www.elastic.co/docs/troubleshoot/security/agentless-integrations.html by re-adding a page at that URL. Uses a snippet so the page can also exist in its [proper location](https://www.elastic.co/docs/solutions/security/get-started/agentless-integrations-faq). This is a temporary solution to make sure links from Google and other search engines work while the full redirect capabilities in V3 are pending.
Previews: 
[/troubleshoot/agentless-integrations.html](https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/1338/troubleshoot/security/agentless-integrations)
[/solutions/security/get-started/agentless-integrations-faq.html](https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/1338/solutions/security/get-started/agentless-integrations-faq)

Uses a snippet for the Agentless Integrations FAQ to resolve broken link

---

deploy-manage/deploy/self-managed/_snippets/config-file-format.md
deploy-manage/deploy/self-managed/_snippets/env-var-setting-subs.md
deploy-manage/deploy/self-managed/configure-elasticsearch.md

Add better connections from elasticsearch config page to jvm and logging docs
Also clarify when things are documenting specifically `elasticsearch.yml`
all changes in https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/1340/deploy-manage/deploy/self-managed/configure-elasticsearch

Add links to config resources

---

solutions/security/configure-elastic-defend/configure-data-volume-for-elastic-endpoint.md

Resolves https://github.com/elastic/docs-content/issues/1214 by adding Elastic Agent versioning info for the different functionalities doc'ed on the **Configure data volume for Elastic Endpoint** page.
Preview: [Configure data volume](https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/1344/solutions/security/configure-elastic-defend/configure-data-volume-for-elastic-endpoint)

Add Agent version info to Endpoint data volume page

---

deploy-manage/deploy/cloud-enterprise/manage-elastic-stack-versions.md

- fixes https://github.com/elastic/docs-content/issues/1358
- updates the "Required downloads" column to "Stack pack download link" 
Intent is to position these as available versions. there was a misconception that this page indicates the stack version that's bundled with the ECE 3.8 release.
leaving the headings on the related [offline install doc](https://www.elastic.co/docs/deploy-manage/deploy/cloud-enterprise/ece-install-offline-images) alone because the context is different

ECE: clarify stack pack column

---

solutions/search/retrievers-overview.md

The API refs are not targeted enough yet.

Update retrievers overview links

---

deploy-manage/monitor/stack-monitoring/eck-stack-monitoring.md

The example for "Connect to an external monitoring elasticsearch cluster" can lead to confusion or seem to be incorrect (because `secretName` is used only for metrics and not for logs), so I added a small explanation about what the config in the example does.

Update ECK monitoring doc for connecting to an external monitoring elasticsearch cluster

---

explore-analyze/machine-learning/anomaly-detection/ml-api-quickref.md

This PR updates the links on the [API quick reference](https://www.elastic.co/docs/explore-analyze/machine-learning/anomaly-detection/ml-api-quickref) page so they navigate to the corresponding GET endpoints instead of the general Anomaly Detection API documentation.
https://github.com/elastic/docs-content/issues/1385

[ML] Updates links on the API quick reference page

---

deploy-manage/upgrade/orchestrator/upgrade-cloud-enterprise.md

A small correction of a KB URL link.
cc @geekpete per our slack
FWIW, https://www.elastic.co/docs/release-notes/cloud-enterprise/known-issues has the correct link:
> In versions from 2.6 to 2.10 included, some or all platform certificates are generated with a 398-day expiration. Installations that ran on these versions, even temporarily, must have their certificates rotated manually before expiry. For details, check [our KB article](https://ela.st/ece-certificate-rotation).
Where
```
check [our KB article](https://ela.st/ece-certificate-rotation)
```

Correct ECE doc KB reference

---

manage-data/lifecycle/index-lifecycle-management.md

This removes the 'Serverless' tag from the [Index Lifecycle Management](https://www.elastic.co/docs/manage-data/lifecycle/index-lifecycle-management) landing page in the docs.

Remove 'Serverless' tag from ILM page

---

solutions/observability/apm/api-keys.md

This method was removed in 9.0,
see https://github.com/elastic/apm-server/issues/14127

[apm] Remove APM Server ApiKey CLI tool from docs.

---

explore-analyze/machine-learning/nlp/ml-nlp-deploy-model.md

[E&A] Fixes link text in NLP model deployment section

---

.github/CODEOWNERS

This PR adds the Ingest docs team as codeowners for Cloud Security files under `/solutions/security/cloud/`.

Updates codeowners for Cloud Security

---

release-notes/elastic-cloud-serverless/known-issues.md

This PR does the following:
- Updates the known issue summary for the Elastic Defend bug that reverted rule customizations when a new integration policy was created. The summary now shows that the bug is resolved.
- Splits the Serverless known issues page into two categories: active and resolved bugs. This change allows users, support, and other important stakeholders to quickly understand whether known issues have been fixed or are still active in Serverless. 
Preview: [Elastic Cloud Serverless known issues](https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/1451/release-notes/elastic-cloud-serverless/known-issues)

[Serverless release notes] Updates known issues page structure

---

deploy-manage/deploy/cloud-on-k8s/configuration-fleet.md
reference/fleet/advanced-kubernetes-managed-by-fleet.md

This adds documentation for the feature implemented in https://github.com/elastic/cloud-on-k8s/pull/8623
Merge target is `eck-3.1.0` so that we can in preparation for the next ECK release merge all pertinent docs at once to main.

Docs for Fleet advanced config in ECK

---

deploy-manage/upgrade/orchestrator/upgrade-cloud-enterprise.md

ECE 4 does only support Elastic Stack 8.0.0 and above, updating this to reflect this fact.
This should be back ported to the current live ECE 4.0 docs .

Update minimum stack version to 8.0.0 for ECE 4

---

deploy-manage/deploy/self-managed/_snippets/etc-elasticsearch.md
deploy-manage/deploy/self-managed/install-elasticsearch-with-debian-package.md
deploy-manage/deploy/self-managed/install-elasticsearch-with-rpm.md

Minor change to fix the package configuration file in the Debian installation guide, which was incorrectly set to the RPM based file.
@shainaraskas : As the content came from a reused snippet we have lost the code formatting. Let me know your preference here. If you want to not use the `snippet` for this block of content or if we keep using it and we lose the code formatting.
If we use \`{{pkg-conf}}\` the substitution doesn't work.
I'm going to write a docs-builder issue to see if we can support inline code blocks with substitutions.
Closes https://github.com/elastic/docs-content/issues/1430

Debian pkg config file updated in snippet

---

manage-data/data-store/templates.md

If we say the priority should be above 500 it should at least be 501
[Current Doc page](https://www.elastic.co/docs/manage-data/data-store/templates)

If we say the priority should be above 500 it should at least be 501

---

solutions/observability/get-started/quickstart-elastic-cloud-otel-endpoint.md

Fixes https://github.com/elastic/observability-docs/issues/4886

Add tech preview note

---

solutions/security/get-started/automatic-import.md

Automatic Import went GA in 8.18 / 9.0 so updating the docs to reflect that

Fixing Automatic Import status to be GA

---

deploy-manage/production-guidance/scaling-considerations.md

duplicate paragraph fixed in production guidance section

removed duplicated paragraph

---

release-notes/fleet-elastic-agent/index.md

This PR fixes a formatting error in the 9.0.2 fleet & agent release notes. No content changes beyond the correction were made.

Fix formatting error in the 9.0.2 release notes

---

solutions/search/vector/knn.md

Reverts elastic/docs-content#1495
A [silly person](https://github.com/leemthompo) thought we already sanitized the unreleased version in the output, but we don't (yet) so this shouldn't have merged (yet).

Revert "Update `recore_vector` preview/GA status in knn.md"

---

deploy-manage/deploy/cloud-enterprise/ece-install-offline-images.md
deploy-manage/deploy/cloud-enterprise/manage-elastic-stack-versions.md

Adds 8.18.2 to the download pages. (Release date May 29)
Release issue: https://github.com/elastic/cloud/issues/141348

Prepare stackpack download pages for 8.18.2 release.

---

release-notes/elastic-cloud-serverless/known-issues.md
release-notes/elastic-security/known-issues.md

Contributes to https://github.com/elastic/docs-content/issues/1548 by adding a known issue about the risk score feature in Serverless and Security 9.x. 
Preview: 
- [Elastic Cloud Serverless known issues](https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/1550/release-notes/elastic-cloud-serverless/known-issues)
- [Security Serverless 9.x known issues](https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/1550/release-notes/elastic-security/known-issues)
**Corresponding PRs**
- 8.x: https://github.com/elastic/security-docs/pull/6866

[Release notes][Serverless & Sec 9.x] Add known issue to release notes for "Entity Risk Score documents eventually fail to persist

---

release-notes/fleet-elastic-agent/index.md
release-notes/fleet-elastic-agent/known-issues.md

This PR adds a known issue affecting Elastic Agent 9.0.0 and 9.0.1 on macOS, where the osquery integration fails due to the removal of the `osquery.app/` directory during installation. A workaround is provided. 
See [#8245](https://github.com/elastic/elastic-agent/issues/8245) for more context.

Add known issue for osquery integration failure on macOS [#1528]

---

deploy-manage/deploy/cloud-enterprise/ece-install-offline-images.md
deploy-manage/deploy/cloud-enterprise/manage-elastic-stack-versions.md

Update download page and offline images.
Related cloud-assets update for 3.8 docs: https://github.com/elastic/cloud-assets/pull/1904

Stack release: 9.0.2 / 8.17.7.

---

release-notes/elastic-cloud-serverless/index.md

Addendum to https://github.com/elastic/docs-content/issues/1610. Updates serverless date to June 2, 2025 (even though it was delayed a day).

Updates serverless changelog date 

---

deploy-manage/monitor/stack-monitoring/eck-stack-monitoring.md

[Preview](https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/1629/deploy-manage/monitor/stack-monitoring/eck-stack-monitoring#enable-stack-monitoring)

Fix typo at eck-stack-monitoring.md

---

deploy-manage/production-guidance/optimize-performance/indexing-speed.md
manage-data/data-store/text-analysis/specify-an-analyzer.md

Issue: https://github.com/elastic/docs-projects/issues/302
- https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/1697/deploy-manage/production-guidance/optimize-performance/indexing-speed#disable-refresh-interval
- https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/1697/manage-data/data-store/text-analysis/specify-an-analyzer#update-analyzers-on-existing-indices

Add refresh_interval and analyzer request examples from old API ref

---

reference/elasticsearch-clients/index.md

When you visit https://www.elastic.co/docs/reference/elasticsearch-clients/, the official Rust client is not listed, despite being listed in the sidebar.
This PR adds the Rust client to the official client list.

Add Rust client to the list of official clients

---

troubleshoot/elasticsearch/task-queue-backlog.md

👋 howdy, team!  I had a typo, sorry. Searches aren't sub-from-writes, so replacing with an asterisk.

Task backlog | Long running search

---

solutions/observability/get-started/quickstart-elastic-cloud-otel-endpoint.md
solutions/observability/get-started/quickstart-unified-kubernetes-observability-with-elastic-distributions-of-opentelemetry-edot.md

Add links to the new opentelemetry://reference/motlp.md` doc.

Add links to mOTLP doc

---

explore-analyze/alerts-cases/watcher/actions.md

This PR adds the ACK Watch API examples to the Watcher -- Actions page as part of the approach to unify API reference documentation.
Related issue: https://github.com/elastic/docs-projects/issues/302

Adds ack_watch example to the  Watcher - Actions page

---

explore-analyze/alerts-cases/watcher/execute-watch.md
explore-analyze/toc.yml

This PR adds the Execute a watch API examples to the Watcher Example watches section as part of the approach to unify API reference documentation.
Related issue: https://github.com/elastic/docs-projects/issues/302

Adds the "Execute a watch" API example page

---

solutions/security/ai/ai-assistant.md

Related to https://github.com/elastic/docs-content/issues/1754
This PR adds a section about the Elastic Managed LLM to the Security AI Assistant docs.

[Security] Adds section about Elastic Managed LLM to Security AI assistant

---

solutions/security/advanced-entity-analytics/privileged-user-monitoring.md
solutions/toc.yml

Adds a hidden placeholder page for privileged user monitoring to enable linking to the future doc from the product onboarding page.

[Security] Adds placeholder page for privileged user monitoring

---

reference/fleet/agent-command-reference.md

Remove unused <hr> tags that were not rendered on the website (possibly carryover from AsciiDoc conversion?)

Fix unused tags not rendering

---

explore-analyze/discover/try-esql.md
explore-analyze/images/keyboard.svg
explore-analyze/query-filter/languages/esql-kibana.md

Batching a few changes for the various ES|QL editor improvements that don't require a lot of docs.
The main need here for newly supported commands and functions is to make the ES|QL reference quicker to find for anyone reading these docs.
- Adding a direct link to the ES|QL syntax docs from a few pages
- Adding a section about keyboard shortcuts supported by the editor
- Moving the LOOKUP_JOIN section from Discover docs to ES|QL editor docs as it's not Discover specific, and to prepare for future improvements around this command (file upload...)
closes: https://github.com/elastic/docs-content/issues/1677
closes: https://github.com/elastic/docs-content/issues/1678
closes: https://github.com/elastic/docs-content/issues/1680
closes: https://github.com/elastic/docs-content/issues/1681
Other …

Small ES|QL editor changes for 9.1

---

release-notes/elastic-security/known-issues.md

Resolves https://github.com/elastic/docs-content/issues/1895.
Preview: [Known issues](https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/1898/release-notes/elastic-security/known-issues)

Adds KB settings known issue to Security known issues

---

deploy-manage/deploy/elastic-cloud/differences-from-other-elasticsearch-offerings.md

Fixes #1934 and removes in preview mentions for Azure and GCP Serverless (in the [Core platform capabilities](https://www.elastic.co/docs/deploy-manage/deploy/elastic-cloud/differences-from-other-elasticsearch-offerings#core-platform-capabilities) table), which are now GA for Serverless regions.

Remove mentions of in preview

---

deploy-manage/users-roles/cluster-or-deployment-auth/elasticsearch-privileges.md
manage-data/data-store/data-streams/failure-store.md

fix for https://github.com/elastic/docs-content/pull/1368

readd cs anchors

---

explore-analyze/alerts-cases/watcher/enable-watcher.md

It seems that the tag was added by mistake as according to the [comparison page](https://www.elastic.co/docs/deploy-manage/deploy/elastic-cloud/differences-from-other-elasticsearch-offerings#elasticsearch), it's not avaialble in Serverless.

Removes applies_to tag for Serverless on Watcher page

---

explore-analyze/visualize.md
explore-analyze/visualize/legacy-editors.md

^^
Also created https://github.com/elastic/docs-content/issues/1949 as I noticed the page is out of date and we never got issues from eng for recent changes
Closes: https://github.com/elastic/platform-docs-team/issues/551

Add note that legacy panel types are hidden in some cases since 9.0

---

reference/security/fields-and-object-schemas/alert-schema.md
solutions/security/detect-and-alert/about-detection-rules.md
solutions/security/detect-and-alert/query-alert-indices.md

Related to https://github.com/elastic/security-team/issues/12799. Updates note that lets users know that they should not modify alert index mappings. Redirects them to runtime fields instead.
Corresponding 8.x PR: https://github.com/elastic/security-docs/pull/6882

[Security][9.x & Serverless] Don't modify index mappings for Alerts indices pt.2

---

.github/workflows/label-community-issues.yml

If this works, we can also get rid of the github secret.

Test and monitor `issue.author_association`

---

solutions/observability/get-started.md

Fixes https://github.com/elastic/opentelemetry/issues/332

Remove some links from Obs Get Started

---

deploy-manage/deploy/cloud-enterprise/migrate-to-podman-5.md

Adds https://www.elastic.co/guide/en/cloud-enterprise/current/ece-podman-5-migration.html to the appropriate doc as a mapped_page.
This is part of the work for https://github.com/elastic/docs-projects/issues/494
In a parallel activity we will request the redirect of that page to https://www.elastic.co/docs/deploy-manage/deploy/cloud-enterprise/migrate-to-podman-5

ECE redirect fix - Migrate to podman

---

deploy-manage/deploy/cloud-enterprise/edit-stack-settings-elasticsearch.md

Adds https://www.elastic.co/guide/en/cloud-enterprise/current/ece-change-user-settings-examples.html to the appropriate doc as a mapped_page.
This is part of the work for https://github.com/elastic/docs-projects/issues/494
In a parallel activity we will request the redirect of that page to https://www.elastic.co/docs/deploy-manage/deploy/cloud-enterprise/edit-stack-settings-elasticsearch
In this case we haven't completely imported / migrated the original document because we don't want to duplicate a random list of settings which are available in the reference doc and also in the narrative docs about specific features.

ECE redirect fix - Elasticsearch settings

---

solutions/search/full-text/create-update-synonyms-api-example.md
solutions/search/full-text/search-with-synonyms.md
solutions/toc.yml

This PR adds the 'Create or update synonyms set API examples' page, as part of the approach to unify API reference documentation.
Related issue: https://github.com/elastic/docs-projects/issues/302

Adds 'Create or update synonyms set API examples' page

---

deploy-manage/deploy/cloud-enterprise/edit-stack-settings-apm.md

Adds https://www.elastic.co/guide/en/cloud-enterprise/current/ece-apm-settings.html to the appropriate doc as a mapped_page.
This is part of the work for https://github.com/elastic/docs-projects/issues/494
In a parallel activity we will request the redirect of that page to https://www.elastic.co/docs/deploy-manage/deploy/cloud-enterprise/edit-stack-settings-apm

ECE redirect fix - APM Settings

---

explore-analyze/alerts-cases/alerts/rule-action-variables.md

Removed the tech preview label from the `alertuuid` action variable, as per request from @ymao1. 
Corresponding 8.x docs updated via: https://github.com/elastic/kibana/pull/226292

[KIBANA][9.x & Serv] Removes tech preview label from `alertuuid` action var 

---

troubleshoot/ingest.md
troubleshoot/ingest/opentelemetry/index.md

Added a link to the EDOT troubleshooting documentation on the main page of the Ingest troubleshooting docs.

Add link to EDOT troubleshooting docs on Ingest troubleshooting main page

---

deploy-manage/deploy/elastic-cloud/differences-from-other-elasticsearch-offerings.md
deploy-manage/deploy/elastic-cloud/restrictions-known-problems.md
deploy-manage/deploy/elastic-cloud/tools-apis.md
explore-analyze/alerts-cases/watcher/enable-watcher.md

As described in https://github.com/elastic/docs-content/issues/1952, email service limits are applicable to both ECH and Serverless deployments.
Currently the ECH limits are described in https://www.elastic.co/docs/explore-analyze/alerts-cases/watcher/enable-watcher#cloud-email-service-limits, and linked from https://www.elastic.co/docs/deploy-manage/deploy/elastic-cloud/restrictions-known-problems#ec-restrictions-watcher.
I've added them [here](https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/2044/deploy-manage/deploy/elastic-cloud/differences-from-other-elasticsearch-offerings#cloud-email-service-limits).
I was doubting between that page and the [Elastic Cloud landing page](https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/2044/deploy-manage/deploy/elastic-cloud) …

Elastic Cloud email service limits added for ECH and Serverless

---

solutions/security/endpoint-response-actions.md
solutions/security/endpoint-response-actions/isolate-host.md

Resolves https://github.com/elastic/docs-content/issues/674 by documenting that endpoint actions are available for events.
Previews:
* [Endpoint response actions](https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/2042/solutions/security/endpoint-response-actions)
* [Isolate a host](https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/2042/solutions/security/endpoint-response-actions/isolate-host)

[Security] Enable endpoint actions in events

---

solutions/search/vector/knn.md

Reverts the reversion in elastic/docs-content#1513 because the [applies_to](https://elastic.github.io/docs-builder/syntax/applies/) now works properly

Update `recore_vector` preview/GA status

---

solutions/observability/observability-ai-assistant.md

This PR closes #2122 and updates the `summarize` function description and removes the `get_apm_timeseries` function.

[Obs AI Assistant] Update summarize function and remove get_apm_timeseries

---

release-notes/elastic-cloud-serverless/index.md

Adds the Serverless changelog for July 15, 2025.

Adds the Serverless changelog for July 15, 2025

---

release-notes/intro/index.md

A few changes to our release notes landing page:
- Text and link to release API doc removed, as we don't have that doc anymore.
- Link to blog post updated to link release announcement blog posts, as it's more accurate in the context of the doc.
- Changed the link to contact elastic support.

API releases link removed, blog link updated

---

solutions/observability/observability-ai-assistant.md

This PR closes [Issue 285](https://github.com/elastic/obs-docs-projects/issues/285) and adds documentation on the Observability AI Assistant multilingual capabilities.

[Observability AI Assistant] Add multilingual capabilities

---

release-notes/elastic-security/index.md

A couple of Rule Management PRs were incorrectly picked up for the 9.1.0 RNs instead of 9.0.4. This PR adds them to the 9.0.4 RNs.

Security 9.0.4 release notes fix

---

solutions/observability/incident-management/create-an-elasticsearch-query-rule.md
solutions/observability/incident-management/create-an-error-count-threshold-rule.md
solutions/observability/incident-management/create-an-inventory-rule.md
solutions/observability/incident-management/create-an-slo-burn-rate-rule.md
solutions/observability/incident-management/create-custom-threshold-rule.md
solutions/observability/incident-management/create-failed-transaction-rate-threshold-rule.md
solutions/observability/incident-management/create-latency-threshold-rule.md
solutions/observability/incident-management/create-log-threshold-rule.md
solutions/observability/incident-management/create-metric-threshold-rule.md

Contributes to https://github.com/elastic/docs-content/issues/2195 by adding docs for the new `context.grouping` action variable that was added to the following Elasticsearch and Observability rules.
**Var available for the following rules in 9.1:**
- [Custom threshold](https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/2336/solutions/observability/incident-management/create-custom-threshold-rule#observability-create-custom-threshold-alert-rule-add-actions) 
- [SLO burn rate](https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/2336/solutions/observability/incident-management/create-an-slo-burn-rate-rule#observability-create-slo-burn-rate-alert-rule-add-actions) 
- [Elasticsearch query](https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/2336/solutions/observa …

[Observability][9.1, 9.2, & Serverless] Docs new `context.grouping` variable added to Obs rules

---

solutions/security/detect-and-alert/about-building-block-rules.md

Contributes to https://github.com/elastic/docs-content/issues/2334 by clarifying that you can add rule notifications to building block rules.
[Preview](https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/2370/solutions/security/detect-and-alert/about-building-block-rules)
**Corresponding 8.19 docs**:
- https://github.com/elastic/security-docs/pull/7013

[Internal][Security]: Building block rule actions

---

deploy-manage/deploy/cloud-enterprise/ece-install-offline-no-registry.md

PR based on [this request](https://github.com/elastic/docs-content/issues/2392):
https://www.elastic.co/docs/deploy-manage/deploy/cloud-enterprise/ece-install-offline-no-registry
In the [air-gapped installation guide](https://www.elastic.co/docs/deploy-manage/deploy/cloud-enterprise/ece-install-offline-no-registry), we instruct users to pull :
```
docker pull docker.elastic.co/cloud-enterprise/elastic-cloud-enterprise:4.1.0
docker pull docker.elastic.co/cloud-release/elasticsearch-cloud-ess:8.18.0
docker pull docker.elastic.co/cloud-release/kibana-cloud:8.18.0
docker pull docker.elastic.co/cloud-release/elastic-agent-cloud:8.18.0
docker pull docker.elastic.co/cloud-release/enterprise-search-cloud:8.18.0
docker pull docker.elastic.co/cloud-release/elasticsearch-cloud-ess:9.0.0
docker pull …
```

Fix Incorrect ECE Version in Air-Gapped Setup Instructions

---

deploy-manage/users-roles/cluster-or-deployment-auth/jwt.md

This PR fixes a typo in the secret config by deleting an extra `1` at the end of the line. This was correct in the 8.x docs, for example: https://www.elastic.co/guide/en/elasticsearch/reference/8.19/jwt-auth-realm.html
[Slack thread](https://elastic.slack.com/archives/CJE3WCFEH/p1754539786659949)

Fixes typo in JWT token doc

---

release-notes/intro/index.md

This page wasn't using version variables.
Pending to determine if the frontmatter allow the version variable, otherwise we should remove it.

Update release notes landing page to use version variables

---

reference/apm-agents/index.md

I cannot see the android sub page.. I guess it was removed and replaced with https://www.elastic.co/docs/reference/opentelemetry/edot-sdks/android

Remove Android from apm agents index

---

.github/ISSUE_TEMPLATE/b-internal-request.yaml

Adds `9.2` to the list of target stack versions in the GitHub issue template

Add 9.2 to the list of target stack versions

---

solutions/security/cloud/asset-disc-aws.md
solutions/security/cloud/asset-disc-azure.md
solutions/security/cloud/asset-disc-gcp.md
solutions/security/cloud/asset-disc.md

Follow up PR to https://github.com/elastic/docs-content/pull/2381, fixes the applies to labels for the Cloud Asset Discovery integration docs. 
Thanks!

Fixes applies to labels for Cloud Asset Discovery integration

---

troubleshoot/ingest/opentelemetry/edot-collector/insufficient-resources-kubestack.md
troubleshoot/ingest/opentelemetry/toc.yml

Fixes https://github.com/elastic/opentelemetry/issues/394
Fixes https://github.com/elastic/opentelemetry-dev/issues/978

Add kubestack troubleshooting

---

deploy-manage/_snippets/autoops-cc-ech-faq.md
deploy-manage/monitor/autoops.md
deploy-manage/monitor/autoops/cc-autoops-as-cloud-connected.md
deploy-manage/monitor/autoops/cc-connect-local-dev-to-autoops.md
deploy-manage/monitor/autoops/cc-connect-self-managed-to-autoops.md
deploy-manage/toc.yml

This PR adds a page explaining [how to connect a local development cluster to AutoOps](https://docs.google.com/document/d/1bhi-ChuqS1lnTkC9fmseXIPC3Y04k1tC8q8g7UE5hpY/edit?tab=t.u0r4otlndm4k#heading=h.wolypdlz1nl2) through Cloud Connect + some small clarifications.
- @arnonst will check for accuracy of the workflow and the code snippets.
- Users of this new **Connect your local development cluster to AutoOps** page will follow almost the same steps as the ones in [Connect your self-managed cluster to AutoOps](https://www.elastic.co/docs/deploy-manage/monitor/autoops/cc-connect-self-managed-to-autoops), so I opted to send them to that page and pointed out the differences in their workflow. Alternatively, we could duplicate all the instructions (in snippets) and edit for the differences, …

[Private preview] Add page about connecting localhost to AutoOps

---

deploy-manage/users-roles/cluster-or-deployment-auth/file-based.md

This lead to confusion with a user recently as it was not clear how to create the roles referenced in the basic-auth secret. 
~LMK if you prefer this to be one of the tip boxes.~ Actually changed my mind and the tip box seems to make more sense here.

Link from file-realm to file-based roles doc

---

explore-analyze/alerts-cases/alerts/alerting-setup.md

Closes #1700. Most Observability rules require `all` privileges, the custom threshold rule, however, only requires the `stack alerts` privilege. This PR updates the Alerts set up docs to show this.

Add custom threshold rule exception to alerting set up docs

---

solutions/security/ai/attack-discovery.md

Replaces `stack: removed 9.1` labels with `stack: ga 9.0` labels for 8.x features whose behavior changed in 9.1.

[Security] Fix inline applies tags in Attack Discovery docs

---

solutions/search/the-search-api.md

Added `_shards.failed` and `_shards.failures` explanation.

Added _shards.failed and _shards.failures explanation

---

deploy-manage/deploy/self-managed/install-kibana-with-docker.md
solutions/observability/apm/apm-server-binary.md

The base image is Red Hat Universal Base Images (UBI) or Wolfi.
Fixes #1575

Updating the info around the Kibana Docker image

---

release-notes/fleet-elastic-agent/index.md

Adds a release notes entry for release 9.1.2. Although no changes were made in Fleet and Elastic Agent between 9.1.1 and 9.1.2, we still need to add an entry specifying this as customers can upgrade to this version.
cc @ebeahan @pierrehilbert

Fleet Server / Elastic Agent 9.1.2 release notes

---

deploy-manage/security/encrypt-deployment-with-customer-managed-encryption-key.md

- Fixes https://github.com/elastic/docs-content-internal/issues/150
- Adds note with workaround to address the domain restricted sharing case for GCP

Add groups workaround for BYOK GCP config

---

troubleshoot/elasticsearch/troubleshoot-ingest-pipelines.md

Removes the gangrenous space in the Update a documentation API link, which was causing a 404.

Fixes Update a document API link

---

release-notes/elastic-cloud-serverless/index.md

Fixes #2584 by creating this week's serverless changelog.

Serverless Changelog 08/18/25

---

release-notes/elastic-observability/known-issues.md

This PR closes #2677 and adds the known issue regarding the Kubernetes OTel quickstart.

[Observability][Known issue] Add Kubernetes OpenTelemetry onboarding issue

---

deploy-manage/deploy/elastic-cloud/differences-from-other-elasticsearch-offerings.md

Fixes https://github.com/elastic/docs-content/issues/1723

Update differences docs for ech vs serverless

---

deploy-manage/deploy/self-managed/install-elasticsearch-with-rpm.md

The author of #1745 is correct, `autorefresh = 1` is not a config option that's available in dnf or yum. However, it is a valid and often used option in [zypper](https://doc.opensuse.org/documentation/tumbleweed/zypper/) (openSUSE distros).
I've added tabs to account for this discrepancy (when creating the repo definition) and using tabs actually fixes the next step as well, which is trying to account for multiple Linux distros commands to install Elasticsearch from an RPM repo.
The RHEL-based commands for installing will also differ based on the version or RHEL you're using, so that tab accounts for RHEL 8 + (when dnf was introduced) and RHEL 7 & earlier for yum.
I've also updated the names of the distros for accuracy:
* Red Hat Enterprise Linux (RHEL)
* openSUSE
* SUSE Linux Enterprise …

Corrects use of autorefresh option

---

solutions/observability/infra-and-hosts/get-started-with-system-metrics.md

Fixes https://github.com/elastic/docs-content/issues/2414

Add link to quickstarts and other edits to Infra get started

---

release-notes/fleet-elastic-agent/index.md

Converts release notes generated in elastic/elastic-agent and elastic/fleet-server to Markdown and adds them to this repo:
* 9.0.6:
*  https://github.com/elastic/elastic-agent/pull/9564
* https://github.com/elastic/fleet-server/pull/5341
* 9.1.3: 
* https://github.com/elastic/elastic-agent/pull/9565
* https://github.com/elastic/fleet-server/pull/5342
cc @ebeahan @pierrehilbert

Fleet Server / Elastic Agent 9.0.6 and 9.1.3 release notes

---

explore-analyze/query-filter/languages/esql-kibana.md

Added a link to ESQL for Elastic Security use cases.

Adds a link to ESQL for Security docs

---

reference/data-analysis/machine-learning/ml-time-functions.md

## Overview
Related to https://github.com/elastic/docs-content/issues/1287
This PR adds a note to the time function page about using `time_of_week` and `time_of_day` in the same anomaly detection job is not recommended.

[ML] Adds recommendation about using time functions

---

solutions/observability/apm/upstream-opentelemetry-collectors-language-sdks.md
solutions/observability/apm/use-opentelemetry-with-apm.md
solutions/observability/get-started/quickstart-elastic-cloud-otel-endpoint.md
solutions/observability/get-started/quickstart-monitor-your-application-performance.md
troubleshoot/ingest/opentelemetry/edot-collector/collector-not-starting.md
troubleshoot/ingest/opentelemetry/edot-sdks/dotnet/index.md
troubleshoot/ingest/opentelemetry/edot-sdks/java/index.md

This replaces instances of "upstream" (related to OpenTelemetry) with "contrib".

Replace upstream with contrib

---

manage-data/ingest.md

Update title to enhance reader scanability and improve SEO.
Leadership recently said, "To truly keep a modern enterprise secure, you need to **_ingest_**, **_retain_** and **_analyze_** all data." [emphasis mine]. "Ingest" is a word that users are likely to scan the TOC for as part of a normal workflow, so let's make it easy for them to find. 
Search terms in headings get higher relevance rankings. By removing "ingest" or "ingestion" from the heading, we're missing an opportunity for better rankings.

[Ingest] Update title for data ingestion documentation

---

deploy-manage/deploy/_snippets/create-serverless-project-intro.md
deploy-manage/deploy/elastic-cloud/create-serverless-project.md
deploy-manage/deploy/elastic-cloud/serverless.md
solutions/search/get-started.md
solutions/search/get-started/keyword-search-python.md
solutions/search/ingest-for-search.md

Relates to https://github.com/elastic/docs-content/issues/1480
This PR:
- creates a drop-down in https://www.elastic.co/docs/solutions/search/get-started to contain project creation tips, similar to https://www.elastic.co/docs/solutions/observability/get-started. To avoid getting out of sync with https://www.elastic.co/docs/deploy-manage/deploy/elastic-cloud/create-serverless-project, the shared content is moved to a snippet.
- adds Information about the authority required to create projects (derived from  https://www.elastic.co/docs/solutions/observability/get-started) to the snippet
- re-uses the same snippet in the "create a project" step in one of the quickstarts
- adds a link from the search ingestion page to the "find your connection details" page
- updates links from the serverless …

Add project creation to Elasticsearch Getting Started

---

manage-data/lifecycle/index-lifecycle-management/policy-apply.md
manage-data/lifecycle/index-lifecycle-management/policy-updates.md

Edu noted that these two pages seem a bit similar, so I'm adding a sentence or two to each to help clarify the scope. Also, the title change is just for better consistency in the navigation pane.
Preview:
- [Manually apply a lifecycle policy to an index](https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/2923/manage-data/lifecycle/index-lifecycle-management/policy-apply)
- [Update or switch a lifecycle policy](https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/2923/manage-data/lifecycle/index-lifecycle-management/policy-updates)
Rel: https://github.com/elastic/docs-content-internal/issues/190

Super small changes to apply/policy pages

---

manage-data/ingest/transform-enrich/error-handling.md
manage-data/ingest/transform-enrich/ingest-lag.md
manage-data/ingest/transform-enrich/readable-maintainable-ingest-pipelines.md

Update mapped pages for my recently released docs

---

release-notes/intro/index.md

Hi, I found a grammatical error in the [release notes page](https://www.elastic.co/docs/release-notes) and fixed it.
**Before**
```text
Release notes cover the all the latest ...
```
**After**: I removed `the`
```text
Release notes cover all the latest ...
```

Fix grammatical error in release notes introduction

---

.gitignore
solutions/search/agent-builder/limitations-known-issues.md

Liam asked if I could help fill in some of the known issues.

add known issues for agent builder

---

redirects.yml

Followup to the following PRs:
https://github.com/elastic/docs-content/pull/2989
https://github.com/elastic/docs-content/pull/2811
We forgot a redirect and so now when someone looks for these pages in google they run into a sad 404

Add redirects for deduplicated roles and privileges pages

---

deploy-manage/monitor/autoops/cc-connect-self-managed-to-autoops.md

Linux is now available as an installation option for Elastic agent in AutoOps for self-managed clusters. 
Closes https://github.com/elastic/docs-content/issues/3047

[Private preview] Unhide Linux as an agent installation option

---

.github/workflows/update-kube-stack-version.yml
scripts/update_kube_stack_version.py

This fixes the script that updates the Kube Stack version in the OTel docs.

Fix kube stack docs automation

---

deploy-manage/deploy/cloud-enterprise/generate-roles-tokens.md

Currently, both the `curl` command and example output appear in the same `sh` block that may confuse users while copying and running the commands.
With this commit, the example outputs are separated from the `curl` commands similar to the command and output shown in https://www.elastic.co/docs/reference/cloud/cloud-enterprise/ece-restful-api-examples-get-deployments.

Separate the curl outputs from the commands

---

solutions/search/agent-builder/kibana-api.md
solutions/search/agent-builder/programmatic-access.md

Key changes:
- Removed "WIP" warning from kibana-api.md
- Updated API reference link from Kibana API to Kibana serverless API (with TODO for when page goes live)
- Because live on serverless now and we will be publishing new Kib serverless pages ASAP
- Reordered programmatic-access.md content to prioritize MCP/A2A over Kibana APIs
- Added tip explaining most users prefer MCP/A2A integration
- Moved Kibana API to bottom of the list

Update agent builder programmatic access 

---

get-started/index.md

An addendum to #2795. Updates the links to point to the Get Started landing pages instead of the solution landing pages.

Updates links on Fundamentals page 

---

deploy-manage/monitor/autoops/cc-cloud-connect-autoops-faq.md

This updates the OTLP port to indicate that it is now exclusively `443` instead of the standard `4318` (which causes issues for some users).

[AutoOps] Update incoming HTTP port for OTLP

---

explore-analyze/elastic-inference/eis.md

Clarified rate limit for search and ingest operations.
8000 docs/minute is worth being clear about

Update rate limit description in eis.md

---

deploy-manage/monitor/autoops/cc-connect-self-managed-to-autoops.md

This PR adds the dedicated Cloud Connect onboarding link to the AutoOps for self-managed clusters page.

Add Cloud Connect onboarding link for new accounts

---

explore-analyze/elastic-inference/eis.md

Removed region availability section from limitations.
This is covered more broadly in the section above (Region and hosting). Also, the wording could lead people to believe they cannot use it unless their solution also resides in AWS us-east-1

Delete region availability details from eis.md

---

explore-analyze/elastic-inference/eis.md

Added a note that deployments and projects in any region/CSP can access the endpoint. Clarified what the Region Avail means for this service

Make the region and CSP flexibility clear

---

explore-analyze/find-and-organize/saved-objects.md

Updates the serverless projects link in the import/export section.

Fix link for serverless projects API

---

release-notes/elastic-cloud-serverless/index.md

Adds the serverless changelog for 10/6/25.

Serverless changelog: October 6, 2025

---

reference/fleet/fleet-settings.md

Removed duplicate section on agent binary download settings and streamlined the content for clarity.
cc @belimawr

Remove duplicate agent binary download settings section

---

troubleshoot/ingest/opentelemetry/edot-sdks/android/index.md

Related to https://github.com/elastic/apm-agent-android/pull/653

Update Android troubleshooting page
