elastic/docs-content

docs/manage-billing-pricing-model.mdx, docs/manage-billing.mdx, docs/manage-your-project-rest-api.mdx, docs/manage-your-project.mdx, docs/service-status.mdx, docs/shared-features/project-settings/project-settings.mdx, docs/sign-up.mdx, docs/what-is-serverless.mdx, serverless-general.docnav.json
Florent spotted some missing files - this was caused by my local main being behind when I did the original merge
=> Add missing files

help-center/discover.mdx, help-center/es-discover.mdx, help-center/obs-discover.mdx, help-center/sec-discover.mdx
Related to https://github.com/elastic/platform-docs-team/issues/371
This PR contains a help center article about Discover. A guided tour within Kibana/Serverless UI about Discover shows some important actions such as sorting on fields, adjusting the table (changing row height), and expanding documents. **This help center article does not repeat the information presented in the guided tour.**
=> Adds Discover help center article

serverless/pages/sign-up.mdx
Slack thread: https://elastic.slack.com/archives/C0563QTARDF/p1717626154005719
=> Use correct serverless link

serverless/pages/manage-your-project-rest-api.mdx
Small edit to fix a link to the API reference site.
=> Fix API site link

.github/ISSUE_TEMPLATE/serverless-ux-bug-bash-issue.yaml
=> Changes title and label

.github/ISSUE_TEMPLATE/serverless-ux-bug-bash-issue.yaml
Adds API docs to the Serverless Docs bug bash issue template
=> Updates Serverless Docs bug bash issue template

serverless/pages/welcome-to-serverless.mdx
closes https://github.com/elastic/docs-content/issues/65
=> Say Elastic Cloud Serverless

serverless/pages/debug-grok-expressions.asciidoc
This PR updates the navigation instructions for the Grok Debugger.
https://github.com/elastic/docs-content/issues/99
=> Updates the navigation instructions for the Grok Debugger

serverless/pages/ingest-your-data-ingest-data-through-integrations-beats.asciidoc
**Page:** https://www.elastic.co/guide/en/serverless/current/elasticsearch-ingest-data-through-beats.html
**Preview:** https://docs-content_bk_209.docs-preview.app.elstc.co/diff
=> Remove Functionbeat as an ingest option

serverless/pages/serverless-differences.asciidoc
=> Remove links to avoid confusion for planned products

serverless/pages/sign-up.asciidoc
Closes https://github.com/elastic/platform-docs-team/issues/576
h/t @Kushmaro for the text
=> Clarify constraints on serverless trial resources

serverless/index-serverless-changelog.asciidoc
Comments out the empty known issues page for the Serverless changelog
=> [Serverless] Hides empty known issues page

serverless/pages/serverless-changelog.asciidoc
Combines 6-Jan features and enhancements sections to match previous serverless changelog entries.
=> Combines features and enhancements

serverless/pages/serverless-changelog.asciidoc
Fixes changelog section title levels for Serverless
=> Fixes changelog section title levels

deploy-manage/deploy/kibana-reporting-configuration.md, deploy-manage/security/secure-settings.md, deploy-manage/users-roles/cluster-or-deployment-auth/saml.md, solutions/observability/apps/service-overview.md, solutions/observability/logs/stream-application-logs.md
Adds IDs needed for cross-repo links.
=> Add IDs needed for cross-repo links

deploy-manage/deploy/cloud-enterprise.md
=> Fix typo in cloud-enterprise.md

solutions/observability/get-started/quickstart-collect-data-with-aws-firehose.md
Fix formatting for tabs that include admonitions
=> [obs] More tab formatting fixes

raw-migrated-files/kibana/kibana/search-ai-assistant.md, solutions/search/rag.md
For https://github.com/elastic/docs-builder/pull/665.
=> Fix classes

reference/ingestion-tools/fleet/logstash-output.md
This is a forward fit of https://github.com/elastic/ingest-docs/pull/1667 into the 9.0 docs.
=> Add details/warning about Logstash pipeline with integrations

solutions/index.md, solutions/toc.yml
Closes https://github.com/elastic/docs-content/issues/655
=> Reorder solutions nav

troubleshoot/security.md, troubleshoot/security/agentless-integrations.md, troubleshoot/security/detection-rules.md, troubleshoot/security/elastic-defend.md, troubleshoot/security/indicators-of-compromise.md
Adds applies tags to Troubleshoot > Security section
Preview: [Security](https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/701/troubleshoot/security)
=> Adds applies tags to Troubleshoot > Security section

solutions/observability/apps/tail-based-sampling.md
Correct typo samling->sampling
=> typo: samling->sampling

explore-analyze/elastic-inference/inference-api/alibabacloud-ai-search-inference-integration.md
Adds the changes of https://github.com/elastic/elasticsearch/pull/124061 to 9.0.0 docs.
=> [Inference] Alibaba Cloud Inference Service adds support for deepseek models

solutions/search/rag.md
=> Update rag.md #814

deploy-manage/production-guidance/optimize-performance/size-shards.md
This is a dupe of https://github.com/elastic/docs-content/pull/716. 
Fixing authorship for CLA.
=> [DOCS] Rewrite of sizing your shards, port from 8.x docs - fix CLA

release-notes/elastic-cloud-serverless/toc.yml, release-notes/elastic-observability/toc.yml, release-notes/elastic-security/toc.yml, release-notes/fleet-elastic-agent/toc.yml, release-notes/index.md, release-notes/intro/index.md, release-notes/intro/toc.yml, release-notes/toc.yml
Makes adjustments to release notes to work with docs-assembler.
=> [assembler] Make adjustments to release notes

deploy-manage/upgrade/ingest-components.md
Contributes to [elastic/docs-projects#247](https://github.com/elastic/docs-projects/issues/247) and [elastic/docs-projects#270](https://github.com/elastic/docs-projects/issues/270).
=> Adds ingest links to upgrade section

explore-analyze/query-filter/tools/grok-debugger.md
Related to https://github.com/elastic/elasticsearch/pull/125663
Removes reliance on temporary redirects in the elasticsearch repo.
=> [docs] Remove reliance on temporary redirects

explore-analyze/visualize/maps.md, get-started/versioning-availability.md, reference/observability/index.md, release-notes/elastic-observability/index.md, release-notes/elastic-security/index.md, release-notes/intro/index.md, solutions/observability.md, solutions/observability/get-started/quickstart-monitor-hosts-with-elastic-agent.md, solutions/search.md, solutions/search/api-quickstarts.md, solutions/security.md
Add missing mapped pages listed in https://docs.google.com/spreadsheets/d/1bQQVc-QwwXDSd24Vw6Q62dnn_9bxsBeAzeWJAdyxdqI/edit?gid=2025227146#gid=2025227146.
=> Add missing mapped pages

deploy-manage/security/aws-privatelink-traffic-filters.md
Additional feedback for https://github.com/elastic/docs-content/pull/958
cc: @alxchalkias 
Related 3.8 PR: https://github.com/elastic/cloud/pull/139501
=> edit vpc language

explore-analyze/ai-assistant.md
=> [E&A] Pulls out mention of default LLM from AI assistant docs

serverless/pages/custom-roles.asciidoc
cherry-picking https://github.com/elastic/docs-content/pull/1039
=> fix rendering issue on custom roles page - backport

get-started/index.md
This should remove the empty row at the top
Source: https://docs-v3-preview.elastic.dev/elastic/docs-content/tree/main/get-started/
https://docs-v3-preview.elastic.dev/elastic/docs-content/pull/1051/get-started/
=> Remove empty row

solutions/security/ai/connect-to-amazon-bedrock.md
Fixes #1081 by removing a duplicate sentence
=> Removes duplicate sentence

reference/fleet/install-elastic-agents.md
=> [Fleet docs] Fix badly formatted variable

deploy-manage/deploy/self-managed/install-kibana-with-debian-package.md
=> [BUG] Updates Kibana install doc 

solutions/search/esql-for-search.md
=> Uncomment blog link in esql for search

solutions/search/esql-for-search.md
=> Add 8.x mapping to esql-for-search.md

solutions/search/cross-cluster-search.md
CCS is currently incorrectly flagged as available on serverless
h/t @shainaraskas
=> Update cross-cluster-search availability

deploy-manage/deploy/cloud-enterprise/default-system-deployment-versions.md
Updated to include default system deployments for ECE versions
- 4.0.0
- 3.8.0
- 3.7.3
- 3.7.2
=> default-system-deployment-versions.md - Update system cluster versions

deploy-manage/users-roles/cluster-or-deployment-auth/jwt.md
Reverts elastic/docs-content#1124
need to wait for 9.1
=> Revert "update JWT realm docs to include at+jwt support"

deploy-manage/deploy/elastic-cloud/regions.md
Closes: https://github.com/elastic/platform-docs-team/issues/668
=> [Merge April 24th] Remove GCP serverless preview tag

solutions/observability/get-started/quickstart-elastic-cloud-otel-endpoint.md
Fixes https://github.com/elastic/observability-docs/issues/4892
=> Fix broken link in quickstart-elastic-cloud-otel-endpoint.md

release-notes/elastic-cloud-serverless/index.md
Adds the Elastic Cloud Serverless features, enhancements, and bug fixes for May 19, 2025.
=> Adds the Serverless changelog for May 19, 2025

reference/fleet/agent-command-reference.md, reference/fleet/otel-agent-transform.md, reference/fleet/otel-agent.md, solutions/observability/apm/attributes.md, solutions/observability/apm/upstream-opentelemetry-collectors-language-sdks.md, solutions/observability/get-started/quickstart-elastic-cloud-otel-endpoint.md
Remove technical preview notices and edit links and other references. 
Contributes to https://github.com/elastic/observability-docs/issues/4891
=> Edit Fleet and APM docs for OTel references

solutions/search/esql-for-search.md
Related to https://github.com/elastic/elasticsearch/pull/128437
Makes full text functions GA in ES|QL
=> Make ESQL Full Text Functions GA

solutions/security/get-started/automatic-import.md
Followup PR to https://github.com/elastic/docs-content/pull/1500 but fixing the value to be more correct per https://github.com/elastic/docs-content/pull/1500#pullrequestreview-2871602684
=> Updated Automatic Import status to be GA

reference/fleet/remote-elasticsearch-output.md
Fix typo in sub formatting in remote-elasticsearch-output.md
=> Fix typo in remote-elasticsearch-output.md

explore-analyze/visualize/maps.md
Remove misleading warning about project availability flagged by @dadoonet
=> Remove misleading warning about serverless project availability in maps.md

release-notes/elastic-cloud-serverless/index.md
Closes https://github.com/elastic/docs-content/issues/1590.
=> Adds Serverless changelog for June 9, 2025

release-notes/elastic-security/index.md
Adds a link to the Kibana release notes from the Security release notes
=> Link to Kibana RN from Security RN

get-started/index.md
=> Centered logos in "Get started"

solutions/search/search-applications.md
=> Remove planning verbiage

deploy-manage/deploy/cloud-enterprise/ece-install-offline-images.md, deploy-manage/deploy/cloud-enterprise/manage-elastic-stack-versions.md
Update download page and offline images.
=> Stack release: 7.17.29 / 8.17.8

deploy-manage/cloud-organization/billing/add-billing-details.md, deploy-manage/cloud-organization/billing/manage-subscription.md, deploy-manage/cloud-organization/billing/monitor-analyze-usage.md, deploy-manage/cloud-organization/billing/update-billing-operational-contacts.md, deploy-manage/cloud-organization/billing/view-billing-history.md, deploy-manage/deploy/elastic-cloud/aws-marketplace.md, deploy-manage/tools/snapshot-and-restore/ec-azure-snapshotting.md, deploy-manage/tools/snapshot-and-restore/ec-gcs-snapshotting.md, deploy-manage/users-roles/cloud-organization/manage-users.md, deploy-manage/users-roles/cloud-organization/user-roles.md
Updated to add missing step on home page + simplify route to Billing and Organization.
Rel: https://github.com/elastic/docs-content/pull/1833
=> [Cloud UI nav redesign] Fix navigation routes in instructions

troubleshoot/monitoring/node-moves-outages.md
=> Removed the "to" typo.

deploy-manage/deploy/elastic-cloud/differences-from-other-elasticsearch-offerings.md
With link to the service description and limits.
Closes https://github.com/elastic/docs-content/issues/1952
=> Added email service to platform capabilities list of ECH and Serverless

release-notes/elastic-security/known-issues.md, release-notes/fleet-elastic-agent/known-issues.md
Documents known issue described in [elastic/endpoint#90](https://github.com/elastic/endpoint/issues/90).
cc @gabriellandau
=> [elastic agent] Document known issue described in elastic/endpoint#90

release-notes/intro/index.md
Fixes https://github.com/elastic/docs-content/issues/2155
=> 8.x link updated to 8.18

deploy-manage/tools/snapshot-and-restore/minio-on-premise-repository.md, solutions/security/ai/ai-assistant.md
Closes: https://github.com/elastic/docs-content-internal/issues/102
Update Security documentation to reflect changes to how the Security AI assistant generates ES|Ql.
=> [Security Solution] [AI assistant] Include in documentation changes to ES|QL generation in the security AI assistant

.github/CODEOWNERS
Update `CODEOWNERS` for `solutions/security/`.
=> Update `CODEOWNERS` for `solutions/security/`

troubleshoot/ingest/opentelemetry/edot-collector/collector-not-starting.md
Fix the navigation title to be consistent with other nav titles in the section
=> Change nav title for consistency

solutions/observability/observability-serverless-feature-tiers.md
Adds link to the Get started pages on the Observability Serverless feature tiers page.
=> [Observability] Add link to Logs Essentials get started

deploy-manage/deploy/elastic-cloud/project-settings.md
Fixes #2560 — corrects an inaccuracy on the Elastic Security feature tiers description page.
=> Fixes EASE feature tier info

solutions/observability/get-started.md, solutions/observability/get-started/logs-essentials.md
This PR adds a note to the main get started page to tell users that it relates to Observability Complete and links to Logs Essentials.
=> add-feature-tiers-note

manage-data/ingest/transform-enrich/readable-maintainable-ingest-pipelines.md
Fixes frontmatter in ingest pipeline doc.
cc @philippkahr
=> Fix frontmatter in ingest pipeline doc

manage-data/migrate/migrate-data-between-elasticsearch-clusters-with-minimal-downtime.md
Clarify one point in the docs about minimal downtime migration.
=> Clarify minimal downtime data migration

deploy-manage/deploy/cloud-enterprise/ece-install-offline-images.md, deploy-manage/deploy/cloud-enterprise/manage-elastic-stack-versions.md
Rel: https://github.com/elastic/cloud/issues/146592
https://github.com/elastic/cloud/issues/146877
=> Release 8.19.4 / 9.1.4

release-notes/elastic-observability/index.md
Updated references for the save button and Synthetics monitor filters in release notes.
=> Fixes links in Obs release notes

scripts/update_kube_stack_version.py
Script couldn't find docset.yml
=> Edit path in script

docset.yml
here's the error I'm correcting
https://github.com/elastic/docs-content/actions/runs/17921598477/job/50957751258#step:11:143
=> Remove unused sub to make CI happy

explore-analyze/visualize/graph.md, explore-analyze/visualize/graph/graph-configuration.md, explore-analyze/visualize/graph/graph-troubleshooting.md, troubleshoot/kibana/graph.md
Rel: https://github.com/elastic/docs-content-internal/issues/357
=> Update serverless status to unavailable in graph.md

deploy-manage/users-roles/cloud-organization/configure-saml-authentication.md
Added a note to the SAML SSO config for DNS TXT removal and claiming domain from multiple orgs
=> Update SAML SSO config for DNS TXT removal

solutions/observability/get-started/logs-essentials.md
Serverless feature tier options were made more visible. I've updated the Logs Essentials onboarding to show this change.
=> [Observability] Update Logs Essentials onboarding

solutions/security/apis.md
Updates the APIs page in Security docs to include a link to all Elastic APIs.
Also adds context to H1 for better SEO.
=> [Securiity] Updates APIs page

deploy-manage/cloud-organization/billing/cloud-hosted-deployment-billing-dimensions.md
just put it in code formatting
=> Fix calculation so it's readable

solutions/search/agent-builder/models.md, solutions/toc.yml
Stubs out a stub page to unlock doc links in Kibana etc.
=> Add stub for agent builder models page
